package otu

var sectorWorlds [][]string

func init() {
	//MENORIAL A
	sectorWorlds = append(sectorWorlds, []string{"Adhara", "A0609", "", "B57A687-8", "Wa Ni", "", "", "G", "A", "Menorial"})
	sectorWorlds = append(sectorWorlds, []string{"Allemange", "A0503", "", "X688000-0", "Ba", "R", "Strend Cluster", "", "A", "Menorial"})
	sectorWorlds = append(sectorWorlds, []string{"Armada", "A0608", "", "A540244-A", "De Lo Ni Po", "", "", "", "A", "Menorial"})
	sectorWorlds = append(sectorWorlds, []string{"Bilke", "A0110", "", "D987341-7", "Ni Lo Ga", "", "Florian League", "G", "A", "Menorial"})
	sectorWorlds = append(sectorWorlds, []string{"Crescent", "0307", "", "B420778-7", "Na Po De", "", "", "G", "A", "Menorial"})
	sectorWorlds = append(sectorWorlds, []string{"Dustpan", "0204", "", "A550779-9", "De Po", "", "", "", "A", "Menorial"})
	sectorWorlds = append(sectorWorlds, []string{"Fomalhaut", "0802", "", "B510200-D", "Lo Va Ni Ht", "", "G", "A", "Menorial"})
	sectorWorlds = append(sectorWorlds, []string{"Hadara", "0809", "", "E311796-7", "Ic Na Lt", "", "", "", "A", "Menorial"})
	sectorWorlds = append(sectorWorlds, []string{"Halka", "0510", "N", "B865544-A", "Ag Ni Ga", "", "Florian League", "", "A", "Menorial"})
	sectorWorlds = append(sectorWorlds, []string{"Heath", "0209", "", "B587532-B", "Ag Ni", "", "G", "A", "Menorial"})
	sectorWorlds = append(sectorWorlds, []string{"Marseilles", "0403", "", "D540312-7", "Lo De Po Ni", "", "Strend Cluster", "G", "A", "Menorial"})
	sectorWorlds = append(sectorWorlds, []string{"Paques", "0404", "", "B9E6400-E", "Fl Ni Ga Lt", "", "", "", "A", "Menorial"})
	sectorWorlds = append(sectorWorlds, []string{"Sable des Etoiles", "0504", "", "B000899-D", "As Na Ht", "", "Strend Cluster", "G", "A", "Menorial"})
	sectorWorlds = append(sectorWorlds, []string{"Sam’s World", "0202", "", "E100856-7", "Na Va", "", "", "G", "A", "Menorial"})
	sectorWorlds = append(sectorWorlds, []string{"Strend", "0505", "N", "B436AFB-E", "Po Hi Ht", "A", "Strend Cluster", "G", "A", "Menorial"})
	sectorWorlds = append(sectorWorlds, []string{"Szirp", "0201", "", "A436538-D", "Ni Ht", "", "", "", "A", "Menorial"})
	sectorWorlds = append(sectorWorlds, []string{"Taltern", "0103", "", "E530240-6", "Ni", "", "", "", "A", "Menorial"})
	sectorWorlds = append(sectorWorlds, []string{"Trossachs", "0310", "", "B897A54-C", "In Hi Ga Ht", "", "Florian League", "G", "A", "Menorial"})
	sectorWorlds = append(sectorWorlds, []string{"Viceroy", "0408", "", "B8D3515-C", "Fl Ni Ga Ht", "", "", "G", "A", "Menorial"})
	sectorWorlds = append(sectorWorlds, []string{"Vip", "0210", "N", "A421644-D", "Na Ni Po Ht", "", "Florian League", "", "A", "Menorial"})
	sectorWorlds = append(sectorWorlds, []string{"Zephyr", "0702", "", "B999545-7", "Ni Ga", "", "", "G", "A", "Menorial"})
	//EGYRN B
	sectorWorlds = append(sectorWorlds, []string{"985-373", "0409", "", "X775000-0", "Ba", "R", "", "", "B", "Egyrn"})
	sectorWorlds = append(sectorWorlds, []string{"Ashley’s Rock", "0801", "", "D100120-7", "Ni Lo Va Lt", "", "G", "B", "Egyrn"})
	sectorWorlds = append(sectorWorlds, []string{"Belgard", "0306", "N", "C571321-9", "Ni Lo", "", "Belgardian Sojurnate", "G", "B", "Egyrn"})
	sectorWorlds = append(sectorWorlds, []string{"Braudel", "0808", "", "X543200-5", "Lo Ni Po Lt", "R", "", "G", "B", "Egyrn"})
	sectorWorlds = append(sectorWorlds, []string{"Carben", "0702", "", "X5555A9-2", "Ag Ni Lt", "R", "", "", "B", "Egyrn"})
	sectorWorlds = append(sectorWorlds, []string{"Eleson", "0508", "", "E541100-8", "Ni Po Lo", "", "Belgardian Sojurnate", "G", "B", "Egyrn"})
	sectorWorlds = append(sectorWorlds, []string{"Ganulph", "0507", "", "X500000-0", "Ba", "R", "", "G", "B", "Egyrn"})
	sectorWorlds = append(sectorWorlds, []string{"Gollere", "0505", "", "D574756-7", "Ag", "", "", "", "B", "Egyrn"})
	sectorWorlds = append(sectorWorlds, []string{"Gorgon", "0205", "", "E590224-6", "De Lo Ni", "", "Belgardian Sojurnate", "G", "B", "Egyrn"})
	sectorWorlds = append(sectorWorlds, []string{"Goria", "0610", "", "E422475-7", "Ni Po", "", "", "", "B", "Egyrn"})
	sectorWorlds = append(sectorWorlds, []string{"Kaldamar", "0401", "", "E745326-7", "Ni Lo", "", "G", "B", "Egyrn"})
	sectorWorlds = append(sectorWorlds, []string{"Nabeth", "0402", "S", "D426579-8", "Ni", "", "Imperium", "G", "B", "Egyrn"})
	sectorWorlds = append(sectorWorlds, []string{"Pa’an", "0109", "", "E649333-5", "Ni Lo Lt", "", "G", "B", "Egyrn"})
	sectorWorlds = append(sectorWorlds, []string{"Selshor", "0602", "", "X430576-6", "De Ni Po Lt", "R", "", "G", "B", "Egyrn"})
	sectorWorlds = append(sectorWorlds, []string{"T’yana", "0802", "", "E568752-7", "Ag Ri", "", "", "", "B", "Egyrn"})
	sectorWorlds = append(sectorWorlds, []string{"Velscur", "0310", "", "X574479-5", "Ni Lt", "R", "G", "B", "Egyrn"})
	sectorWorlds = append(sectorWorlds, []string{"Vior", "0805", "", "D500401-7", "Va Ni Lt", "", "G", "B", "Egyrn"})
	sectorWorlds = append(sectorWorlds, []string{"Walei", "0102", "", "E7B4776-8", "Fl Lt", "", "G", "B", "Egyrn"})
}
