package otu

import (
	"fmt"
	"strings"
)

var troyanReachData [][]string

func init() {
	//MENORIAL A
	troyanReachData = append(troyanReachData, []string{"Adhara", "0609", "", "B57A687-8", "Wa Ni", "", "", "G", "A", "Menorial"})
	troyanReachData = append(troyanReachData, []string{"Allemange", "0503", "", "X688000-0", "Ba", "R", "Strend Cluster", "", "A", "Menorial"})
	troyanReachData = append(troyanReachData, []string{"Armada", "0608", "", "A540244-A", "De Lo Ni Po", "", "", "", "A", "Menorial"})
	troyanReachData = append(troyanReachData, []string{"Bilke", "0110", "", "D987341-7", "Ni Lo Ga", "", "Florian League", "G", "A", "Menorial"})
	troyanReachData = append(troyanReachData, []string{"Crescent", "0307", "", "B420778-7", "Na Po De", "", "", "G", "A", "Menorial"})
	troyanReachData = append(troyanReachData, []string{"Dustpan", "0204", "", "A550779-9", "De Po", "", "", "", "A", "Menorial"})
	troyanReachData = append(troyanReachData, []string{"Fomalhaut", "0802", "", "B510200-D", "Lo Va Ni Ht", "", "", "G", "A", "Menorial"})
	troyanReachData = append(troyanReachData, []string{"Hadara", "0809", "", "E311796-7", "Ic Na Lt", "", "", "", "A", "Menorial"})
	troyanReachData = append(troyanReachData, []string{"Halka", "0510", "N", "B865544-A", "Ag Ni Ga", "", "Florian League", "", "A", "Menorial"})
	troyanReachData = append(troyanReachData, []string{"Heath", "0209", "", "B587532-B", "Ag Ni", "", "", "G", "A", "Menorial"})
	troyanReachData = append(troyanReachData, []string{"Marseilles", "0403", "", "D540312-7", "Lo De Po Ni", "", "Strend Cluster", "G", "A", "Menorial"})
	troyanReachData = append(troyanReachData, []string{"Paques", "0404", "", "B9E6400-E", "Fl Ni Ga Lt", "", "", "", "A", "Menorial"})
	troyanReachData = append(troyanReachData, []string{"Sable des Etoiles", "0504", "", "B000899-D", "As Na Ht", "", "Strend Cluster", "G", "A", "Menorial"})
	troyanReachData = append(troyanReachData, []string{"Sam’s World", "0202", "", "E100856-7", "Na Va", "", "", "G", "A", "Menorial"})
	troyanReachData = append(troyanReachData, []string{"Strend", "0505", "N", "B436AFB-E", "Po Hi Ht", "A", "Strend Cluster", "G", "A", "Menorial"})
	troyanReachData = append(troyanReachData, []string{"Szirp", "0201", "", "A436538-D", "Ni Ht", "", "", "", "A", "Menorial"})
	troyanReachData = append(troyanReachData, []string{"Taltern", "0103", "", "E530240-6", "Ni", "", "", "", "A", "Menorial"})
	troyanReachData = append(troyanReachData, []string{"Trossachs", "0310", "", "B897A54-C", "In Hi Ga Ht", "", "Florian League", "G", "A", "Menorial"})
	troyanReachData = append(troyanReachData, []string{"Viceroy", "0408", "", "B8D3515-C", "Fl Ni Ga Ht", "", "", "G", "A", "Menorial"})
	troyanReachData = append(troyanReachData, []string{"Vip", "0210", "N", "A421644-D", "Na Ni Po Ht", "", "Florian League", "", "A", "Menorial"})
	troyanReachData = append(troyanReachData, []string{"Zephyr", "0702", "", "B999545-7", "Ni Ga", "", "", "G", "A", "Menorial"})
	//EGYRN B
	troyanReachData = append(troyanReachData, []string{"985-373", "0409", "", "X775000-0", "Ba", "R", "", "", "B", "Egyrn"})
	troyanReachData = append(troyanReachData, []string{"Ashley’s Rock", "0801", "", "D100120-7", "Ni Lo Va Lt", "", "", "G", "B", "Egyrn"})
	troyanReachData = append(troyanReachData, []string{"Belgard", "0306", "N", "C571321-9", "Ni Lo", "", "Belgardian Sojurnate", "G", "B", "Egyrn"})
	troyanReachData = append(troyanReachData, []string{"Braudel", "0808", "", "X543200-5", "Lo Ni Po Lt", "R", "", "G", "B", "Egyrn"})
	troyanReachData = append(troyanReachData, []string{"Carben", "0702", "", "X5555A9-2", "Ag Ni Lt", "R", "", "", "B", "Egyrn"})
	troyanReachData = append(troyanReachData, []string{"Eleson", "0508", "", "E541100-8", "Ni Po Lo", "", "Belgardian Sojurnate", "G", "B", "Egyrn"})
	troyanReachData = append(troyanReachData, []string{"Ganulph", "0507", "", "X500000-0", "Ba", "R", "", "G", "B", "Egyrn"})
	troyanReachData = append(troyanReachData, []string{"Gollere", "0505", "", "D574756-7", "Ag", "", "", "", "B", "Egyrn"})
	troyanReachData = append(troyanReachData, []string{"Gorgon", "0205", "", "E590224-6", "De Lo Ni", "", "Belgardian Sojurnate", "G", "B", "Egyrn"})
	troyanReachData = append(troyanReachData, []string{"Goria", "0610", "", "E422475-7", "Ni Po", "", "", "", "B", "Egyrn"})
	troyanReachData = append(troyanReachData, []string{"Kaldamar", "0401", "", "E745326-7", "Ni Lo", "", "", "G", "B", "Egyrn"})
	troyanReachData = append(troyanReachData, []string{"Nabeth", "0402", "S", "D426579-8", "Ni", "", "Imperium", "G", "B", "Egyrn"})
	troyanReachData = append(troyanReachData, []string{"Pa’an", "0109", "", "E649333-5", "Ni Lo Lt", "", "", "G", "B", "Egyrn"})
	troyanReachData = append(troyanReachData, []string{"Selshor", "0602", "", "X430576-6", "De Ni Po Lt", "R", "", "G", "B", "Egyrn"})
	troyanReachData = append(troyanReachData, []string{"T’yana", "0802", "", "E568752-7", "Ag Ri", "", "", "", "B", "Egyrn"})
	troyanReachData = append(troyanReachData, []string{"Velscur", "0310", "", "X574479-5", "Ni Lt", "R", "", "G", "B", "Egyrn"})
	troyanReachData = append(troyanReachData, []string{"Vior", "0805", "", "D500401-7", "Va Ni Lt", "", "", "G", "B", "Egyrn"})
	troyanReachData = append(troyanReachData, []string{"Walei", "0102", "", "E7B4776-8", "Fl Lt", "", "", "G", "B", "Egyrn"})
	//PAX RULIN C
	troyanReachData = append(troyanReachData, []string{"Alexin", "0805", "", "B000420-C", "Ni As Ht", "", "Imperium", "", "C", "Pax Rulin"})
	troyanReachData = append(troyanReachData, []string{"Bantral", "0306", "S", "C886589-9", "Ag Ni Ga", "", "", "G", "C", "Pax Rulin"})
	troyanReachData = append(troyanReachData, []string{"Berengaria", "0505", "N S", "B566644-7", "Ag Ni Ri", "", "Imperium", "G", "C", "Pax Rulin"})
	troyanReachData = append(troyanReachData, []string{"Candia", "0201", "", "D4006A9-7", "Na Ni Va Lt", "", "", "G", "C", "Pax Rulin"})
	troyanReachData = append(troyanReachData, []string{"Caraz", "0706", "N", "E311959-A", "De Hi Ic In Na", "A", "Imperium", "G", "C", "Pax Rulin"})
	troyanReachData = append(troyanReachData, []string{"Cyan", "0502", "WS", "C5689B9-A", "Hi", "A", "Imperium", "", "C", "Pax Rulin"})
	troyanReachData = append(troyanReachData, []string{"Doradon", "0602", "S", "A400369-B", "Ni Va Lo", "", "Imperium", "", "C", "Pax Rulin"})
	troyanReachData = append(troyanReachData, []string{"Islent", "0802", "", "BAC0789-9", "De", "A", "Imperium", "G", "C", "Pax Rulin"})
	troyanReachData = append(troyanReachData, []string{"Kryslion", "0402", "", "D583AA9-9", "Hi", "", "Imperium", "", "C", "Pax Rulin"})
	troyanReachData = append(troyanReachData, []string{"Kydde", "0210", "", "B644779-5", "Ag Lt", "", "", "G", "C", "Pax Rulin"})
	troyanReachData = append(troyanReachData, []string{"Magen", "0709", "", "C543550-9", "Ni Po", "", "Senlis Foederate", "G", "C", "Pax Rulin"})
	troyanReachData = append(troyanReachData, []string{"Orsasch", "0408", "", "E541364-7", "Ni Po Lo", "", "Senlis Foederate", "G", "C", "Pax Rulin"})
	troyanReachData = append(troyanReachData, []string{"Pax Rulin", "0604", "N", "A402231-E", "Ic Lo Ni Po Va Ht", "", "Imperium", "G", "C", "Pax Rulin"})
	troyanReachData = append(troyanReachData, []string{"Perrior", "0603", "N", "A633966-B", "Na Po Hi", "", "Imperium", "", "C", "Pax Rulin"})
	troyanReachData = append(troyanReachData, []string{"Rhysk", "0704", "", "X413730-7", "Ic Na Po Lt", "R", "Imperium", "G", "C", "Pax Rulin"})
	troyanReachData = append(troyanReachData, []string{"Senlis", "0508", "", "B671633-A", "Ni Ht", "", "Senlis Foederate", "", "C", "Pax Rulin"})
	//GAZULIN D
	troyanReachData = append(troyanReachData, []string{"627-301", "0603", "R", "X000120-7", "As Lo Ni", "R", "Imperium", "G", "D", "Gazulin"})
	troyanReachData = append(troyanReachData, []string{"Belt-9", "0202", "", "B000213-E", "As Lo Ni Ht", "", "Imperium", "G", "D", "Gazulin"})
	troyanReachData = append(troyanReachData, []string{"Bleak", "0502", "S", "C9C6229-9", "Ni Lo Fl", "", "Imperium", "G", "D", "Gazulin"})
	troyanReachData = append(troyanReachData, []string{"Corben", "0304", "N", "E545455-8", "Ag Ni", "", "Imperium", "G", "D", "Gazulin"})
	troyanReachData = append(troyanReachData, []string{"Fintor", "0407", "", "B540344-7", "Po Ni De Lo", "", "Imperium", "G", "D", "Gazulin"})
	troyanReachData = append(troyanReachData, []string{"Gazulin", "0308", "N S", "AA86887-B", "Ri", "", "Imperium", "G", "D", "Gazulin"})
	troyanReachData = append(troyanReachData, []string{"Iscand", "0504", "N", "B795553-B", "Ag Ni", "", "Imperium", "G", "D", "Gazulin"})
	troyanReachData = append(troyanReachData, []string{"Junction", "0404", "", "B763776-6", "Ri", "", "Imperium", "G", "D", "Gazulin"})
	troyanReachData = append(troyanReachData, []string{"Labora", "0101", "", "B533544-7", "Po Ni", "", "Imperium", "G", "D", "Gazulin"})
	troyanReachData = append(troyanReachData, []string{"MacDermont", "0401", "", "D200768-8", "Va Na", "A", "Imperium", "G", "D", "Gazulin"})
	troyanReachData = append(troyanReachData, []string{"Mirage", "0509", "", "A560676-A", "De Ni Ri", "", "Imperium", "G", "D", "Gazulin"})
	troyanReachData = append(troyanReachData, []string{"Neumann", "0705", "N", "B876AA9-D", "In Hi Ht", "", "Imperium", "G", "D", "Gazulin"})
	troyanReachData = append(troyanReachData, []string{"O’Keefe", "0309", "S", "D879625-7", "Ni", "", "Imperium", "G", "D", "Gazulin"})
	troyanReachData = append(troyanReachData, []string{"Peridot", "0405", "N", "B989894-A", "Ri", "", "Imperium", "", "D", "Gazulin"})
	troyanReachData = append(troyanReachData, []string{"Ploderash", "0707", "", "D303696-8", "Ic Na Ni Va", "", "Imperium", "", "D", "Gazulin"})
	troyanReachData = append(troyanReachData, []string{"Susanawo", "0510", "", "D68A430-5", "Ni Wa Lt", "", "Imperium", "G", "D", "Gazulin"})
	//YGGDRASIL E
	troyanReachData = append(troyanReachData, []string{"Bolsush", "0119", "", "D585741-6", "Ag Ri", "", "Florian League", "G", "E", "Yggdrasil"})
	troyanReachData = append(troyanReachData, []string{"Boronu", "0614", "", "B966741-A", "Ag Ri", "", "Florian League", "G", "E", "Yggdrasil"})
	troyanReachData = append(troyanReachData, []string{"Cimmen", "0320", "", "E7CO140-9", "De Lo Ni", "", "Florian League", "G", "E", "Yggdrasil"})
	troyanReachData = append(troyanReachData, []string{"Daruf", "0116", "", "D540358-5", "Ni Po De Lo Lt", "", "Florian League", "G", "E", "Yggdrasil"})
	troyanReachData = append(troyanReachData, []string{"Fissolon", "0318", "", "B69A742-8", "Wa", "", "Florian League", "G", "E", "Yggdrasil"})
	troyanReachData = append(troyanReachData, []string{"Floria", "0213", "N", "A567942-F", "Hi Ht Na", "", "Florian League", "G", "E", "Yggdrasil"})
	troyanReachData = append(troyanReachData, []string{"Forandin", "0716", "N", "BA89646-9", "Ri Ni", "", "Florian League", "G", "E", "Yggdrasil"})
	troyanReachData = append(troyanReachData, []string{"Garnl", "0516", "", "E884940-8", "Hi", "", "Florian League", "G", "E", "Yggdrasil"})
	troyanReachData = append(troyanReachData, []string{"Ilnest", "0616", "N", "B686347-9", "Ni Lo", "", "Florian League", "G", "E", "Yggdrasil"})
	troyanReachData = append(troyanReachData, []string{"Insec", "0317", "N", "A421542-E", "Ni Po", "", "Florian League", "G", "E", "Yggdrasil"})
	troyanReachData = append(troyanReachData, []string{"Kabal", "0319", "F", "B587147-B", "Ni Lo", "", "Florian League", "G", "E", "Yggdrasil"})
	troyanReachData = append(troyanReachData, []string{"Lucind", "0416", "", "B560642-9", "De Ni Ri", "", "Florian League", "G", "E", "Yggdrasil"})
	troyanReachData = append(troyanReachData, []string{"Odin", "0811", "", "B20149B-8", "Ni Ic Va", "A", "", "G", "E", "Yggdrasil"})
	troyanReachData = append(troyanReachData, []string{"Picard", "0417", "", "D679646-7", "Ni", "", "Florian League", "G", "E", "Yggdrasil"})
	troyanReachData = append(troyanReachData, []string{"Sif", "0820", "", "A765867-7", "Ri", "", "", "G", "E", "Yggdrasil"})
	troyanReachData = append(troyanReachData, []string{"Tefsi", "0418", "N", "B994449-B", "Ni", "", "Florian League", "G", "E", "Yggdrasil"})
	troyanReachData = append(troyanReachData, []string{"Thor", "0813", "", "D669577-5", "Ni Lt", "", "", "G", "E", "Yggdrasil"})
	troyanReachData = append(troyanReachData, []string{"Thrush", "0220", "", "A436246-C", "Ni Lo Ht", "", "Florian League", "G", "E", "Yggdrasil"})
	troyanReachData = append(troyanReachData, []string{"Tibolt", "0415", "", "C575744-8", "Ag", "", "Florian League", "", "E", "Yggdrasil"})
	troyanReachData = append(troyanReachData, []string{"Vorn", "0218", "N", "B611640-9", "Ic Na Ni", "", "Florian League", "G", "E", "Yggdrasil"})
	troyanReachData = append(troyanReachData, []string{"Yggdrasil", "0815", "", "B5507CD-8", "Po De", "A", "Imperium Client State", "", "E", "Yggdrasil"})
	troyanReachData = append(troyanReachData, []string{"Zimt", "0713", "", "C547546-9", "Ag Ni", "", "Florian League", "G", "E", "Yggdrasil"})
	//DPRES F
	troyanReachData = append(troyanReachData, []string{"291-540", "0206", "", "EABA000-0", "Ba", "", "", "G", "F", "Dpres"})
	troyanReachData = append(troyanReachData, []string{"Acis", "0809", "", "B885796-A", "Ag Ri", "", "", "G", "F", "Dpres"})
	troyanReachData = append(troyanReachData, []string{"Caldos", "0507", "", "B530879-6", "Na Ni Po De", "", "", "G", "F", "Dpres"})
	troyanReachData = append(troyanReachData, []string{"Connaught", "0205", "", "D431153-9", "Po Ni Lo", "", "", "", "F", "Dpres"})
	troyanReachData = append(troyanReachData, []string{"Delta Theta", "0410", "", "B501610-9", "Ic Na Ni Va", "", "", "G", "F", "Dpres"})
	troyanReachData = append(troyanReachData, []string{"Dostoevsky", "0308", "R", "B678673-A", "Ag Ni An", "", "Imperium Client State", "G", "F", "Dpres"})
	troyanReachData = append(troyanReachData, []string{"Dpres", "0105", "N", "B631689-A", "Na Ni Po", "", "Imperium Client State", "G", "F", "Dpres"})
	troyanReachData = append(troyanReachData, []string{"Gabriel", "0304", "", "C310100-B", "Ni Lo", "", "Imperium Client State", "G", "F", "Dpres"})
	troyanReachData = append(troyanReachData, []string{"Hecarda", "0609", "", "B560332-9", "De Ni Lo", "", "", "G", "F", "Dpres"})
	troyanReachData = append(troyanReachData, []string{"Janus", "0406", "", "C575321-7", "Ni Lo", "", "", "", "F", "Dpres"})
	troyanReachData = append(troyanReachData, []string{"Lacidaeus", "0509", "", "D100786-7", "Na Ni Va Lt", "", "", "G", "F", "Dpres"})
	troyanReachData = append(troyanReachData, []string{"Sagan", "0607", "", "C796453-8", "Ag Ni", "", "", "G", "F", "Dpres"})
	troyanReachData = append(troyanReachData, []string{"Solaria", "0104", "", "B665734-8", "Ag", "", "", "G", "F", "Dpres"})
	troyanReachData = append(troyanReachData, []string{"Thalassa", "0803", "", "B88A889-8", "Wa Ri", "", "", "G", "F", "Dpres"})
	troyanReachData = append(troyanReachData, []string{"Tktk", "0808", "", "D542640-6", "Po Ni", "", "", "G", "F", "Dpres"})
	troyanReachData = append(troyanReachData, []string{"Tlazolteotl", "0604", "", "D5409CD-7", "In Po De Hi", "A", "", "G", "F", "Dpres"})
	troyanReachData = append(troyanReachData, []string{"Torrance", "0409", "", "E560256-4", "De Ni Lo Lt", "", "Na", "G", "F", "Dpres"})
	troyanReachData = append(troyanReachData, []string{"Tyr", "0608", "", "A551557-B", "Ni Po", "", "Na", "G", "F", "Dpres"})
	//SINDAL G
	troyanReachData = append(troyanReachData, []string{"Ace", "0109", "", "E7A0889-9", "De Lt", "A", "", "", "G", "Sindal"})
	troyanReachData = append(troyanReachData, []string{"Albe", "0601", "", "A540A98-E", "De Hi In Po Ht", "", "Imperium", "G", "G", "Sindal"})
	troyanReachData = append(troyanReachData, []string{"Borite", "0609", "", "E655796-4", "Ag Lt", "", "", "G", "G", "Sindal"})
	troyanReachData = append(troyanReachData, []string{"Chalchiutlicu", "0704", "", "B76A787-7", "Ri Wa", "", "", "G", "G", "Sindal"})
	troyanReachData = append(troyanReachData, []string{"Cordillon", "0801", "", "C431210-B", "Po Ni Lo Ht", "", "Imperium", "G", "G", "Sindal"})
	troyanReachData = append(troyanReachData, []string{"Dolberg", "0503", "", "BAF889D-B", "Fl", "A", "", "", "G", "Sindal"})
	troyanReachData = append(troyanReachData, []string{"Homestead", "0105", "", "D561250-6", "Ni De Lo", "", "", "G", "G", "Sindal"})
	troyanReachData = append(troyanReachData, []string{"Marduk", "0510", "", "C577436-5", "Ni Lt", "", "", "G", "G", "Sindal"})
	troyanReachData = append(troyanReachData, []string{"Noricum", "0408", "", "D8867BB-1", "Ag Lt", "A", "", "G", "G", "Sindal"})
	troyanReachData = append(troyanReachData, []string{"Number One", "0208", "", "C9D6778-9", "Fl", "", "", "G", "G", "Sindal"})
	troyanReachData = append(troyanReachData, []string{"Oghma", "0410", "", "B534754-9", "Ic", "", "", "G", "G", "Sindal"})
	troyanReachData = append(troyanReachData, []string{"Palindrome", "0606", "", "B433334-B", "Po Ni Lo", "", "", "G", "G", "Sindal"})
	troyanReachData = append(troyanReachData, []string{"Realgar", "0603", "", "B540444-A", "De Ni Po", "", "Imperium", "G", "G", "Sindal"})
	troyanReachData = append(troyanReachData, []string{"Salif", "0206", "", "A6236A6-A", "Po Na Ni", "", "", "G", "G", "Sindal"})
	troyanReachData = append(troyanReachData, []string{"Thebus", "0309", "", "B534320-7", "Po Ni Lo", "", "", "G", "G", "Sindal"})
	troyanReachData = append(troyanReachData, []string{"Theev", "0506", "N", "A434500-F", "Na Ni Ht", "A", "", "G", "G", "Sindal"})
	troyanReachData = append(troyanReachData, []string{"Vume", "0505", "", "B100477-C", "Ni Va An", "", "", "G", "G", "Sindal"})
	//TOBIA H
	troyanReachData = append(troyanReachData, []string{"971-852", "0404", "", "E78A000-0", "Ba", "A", "Imperium", "G", "H", "Tobia"})
	troyanReachData = append(troyanReachData, []string{"Ardasii", "0405", "N", "B550684-9", "Ni De Po", "", "Imperium", "", "H", "Tobia"})
	troyanReachData = append(troyanReachData, []string{"Attee", "0706", "", "C7529AE-5", "Po Hi", "A", "Imperium", "G", "H", "Tobia"})
	troyanReachData = append(troyanReachData, []string{"Ayldem", "0603", "N", "A540784-C", "Po De", "A", "Imperium", "G", "H", "Tobia"})
	troyanReachData = append(troyanReachData, []string{"Batav", "0809", "", "B5A8764-A", "Fl An", "", "Imperium", "", "H", "Tobia"})
	troyanReachData = append(troyanReachData, []string{"Berg", "0802", "N", "A675542-B", "Ag Ni", "", "Imperium", "", "H", "Tobia"})
	troyanReachData = append(troyanReachData, []string{"Boulder", "0107", "", "B100758-9", "Va Na", "", "Imperium", "", "H", "Tobia"})
	troyanReachData = append(troyanReachData, []string{"Darchona", "0502", "", "B59A742-A", "Wa", "", "Imperium", "G", "H", "Tobia"})
	troyanReachData = append(troyanReachData, []string{"Dimorus", "0601", "", "D300755-7", "Na Va", "", "Imperium", "", "H", "Tobia"})
	troyanReachData = append(troyanReachData, []string{"Empire", "0301", "N", "B679334-C", "Ni Lo", "", "Imperium", "G", "H", "Tobia"})
	troyanReachData = append(troyanReachData, []string{"Eshadi", "0707", "", "B431358-E", "Ni Po Lo", "", "Imperium", "G", "H", "Tobia"})
	troyanReachData = append(troyanReachData, []string{"Exocet", "0110", "", "A574126-8", "Ni Lo", "", "", "G", "H", "Tobia"})
	troyanReachData = append(troyanReachData, []string{"Fist", "0508", "", "B789430-C", "Ni", "", "Imperium", "G", "H", "Tobia"})
	troyanReachData = append(troyanReachData, []string{"Gor", "0204", "", "C868677-3", "Ag Ni Ri", "", "Imperium", "", "H", "Tobia"})
	troyanReachData = append(troyanReachData, []string{"Hexx", "0305", "N", "B78A577-D", "Ni Wa", "", "Imperium", "G", "H", "Tobia"})
	troyanReachData = append(troyanReachData, []string{"Hradus", "0304", "S", "B54699B-7", "In Hi", "A", "Imperium", "G", "H", "Tobia"})
	troyanReachData = append(troyanReachData, []string{"Iilgan", "0309", "", "C567787-8", "Ag Ri", "", "", "G", "H", "Tobia"})
	troyanReachData = append(troyanReachData, []string{"Imisaa", "0506", "N", "B520867-7", "Na Po De", "", "Imperium", "G", "H", "Tobia"})
	troyanReachData = append(troyanReachData, []string{"Intelia", "0202", "", "C574653-6", "Ag Ni", "", "Imperium", "G", "H", "Tobia"})
	troyanReachData = append(troyanReachData, []string{"Kedus", "0803", "", "D867400-3", "Ni", "", "Imperium", "G", "H", "Tobia"})
	troyanReachData = append(troyanReachData, []string{"Khaliki", "0701", "", "D31156B-9", "Ic Ni", "", "Imperium", "G", "H", "Tobia"})
	troyanReachData = append(troyanReachData, []string{"Nekrino", "0105", "N", "A788400-C", "Ni", "", "Imperium", "G", "H", "Tobia"})
	troyanReachData = append(troyanReachData, []string{"New", "0606", "S", "D66668A-5", "Ri Ni Ag", "", "Imperium", "G", "H", "Tobia"})
	troyanReachData = append(troyanReachData, []string{"New Moscow", "0709", "", "B76779A-7", "Ag Ri", "", "Imperium", "", "H", "Tobia"})
	troyanReachData = append(troyanReachData, []string{"Our Planet", "0602", "", "B687100-A", "Ni Lo", "", "Imperium", "G", "H", "Tobia"})
	troyanReachData = append(troyanReachData, []string{"Pandora", "0410", "", "B878313-B", "Ni Lo", "", "", "G", "H", "Tobia"})
	troyanReachData = append(troyanReachData, []string{"Pichot", "0605", "", "E546330-5", "Ni Lo", "", "Imperium", "G", "H", "Tobia"})
	troyanReachData = append(troyanReachData, []string{"Pryme", "0103", "", "B58668B-9", "Ag Ni Ri", "", "Imperium", "G", "H", "Tobia"})
	troyanReachData = append(troyanReachData, []string{"Sabruse", "0505", "R", "EAC8343-9", "Fl Lo Ni", "", "Imperium", "", "H", "Tobia"})
	troyanReachData = append(troyanReachData, []string{"Saurus", "0403", "", "A550543-B", "De Ni Po", "", "Imperium", "G", "H", "Tobia"})
	troyanReachData = append(troyanReachData, []string{"Scaladon", "0206", "", "AAD98DH-A", "Fl", "A", "Imperium", "", "H", "Tobia"})
	troyanReachData = append(troyanReachData, []string{"Simok", "0703", "", "D9A08CC-8", "De", "A", "Imperium", "G", "H", "Tobia"})
	troyanReachData = append(troyanReachData, []string{"Tobia", "0805", "N", "A544A55-F", "In Hi", "", "Imperium", "G", "H", "Tobia"})
	troyanReachData = append(troyanReachData, []string{"Wildeman", "0409", "", "B431674-C", "Ic Na Ni Va", "", "", "G", "H", "Tobia"})
	//NORA'A I
	troyanReachData = append(troyanReachData, []string{"Aftye", "0102", "", "A560343-D", "Ni De Lo Ht", "", "Hierate", "G", "I", "Nora'a"})
	troyanReachData = append(troyanReachData, []string{"Ahaikhea", "0106", "ACS", "B422423-9", "Ag Ni Po", "", "Hierate", "G", "I", "Nora'a"})
	troyanReachData = append(troyanReachData, []string{"Alirar", "0805", "ACS", "A55557A-C", "Ag Ni Ht", "", "Glorious Empire", "G", "I", "Nora'a"})
	troyanReachData = append(troyanReachData, []string{"Aowaih", "0409", "ACS", "B5866A7-A", "Ag Ni Ri Ht", "", "Hierate", "G", "I", "Nora'a"})
	troyanReachData = append(troyanReachData, []string{"Dalfi", "0202", "", "C550345-9", "De Po Ni Lo", "", "Florian League", "", "I", "Nora'a"})
	troyanReachData = append(troyanReachData, []string{"Eahaw", "0803", "", "E523000-0", "Ba", "", "Hierate", "G", "I", "Nora'a"})
	troyanReachData = append(troyanReachData, []string{"Eawatrye", "0107", "ACS", "B8B5756-C", "Fl Ht", "", "Hierate", "G", "I", "Nora'a"})
	troyanReachData = append(troyanReachData, []string{"Ehaealir", "0809", "", "B63657B-9", "Ni", "", "Hierate", "", "I", "Nora'a"})
	troyanReachData = append(troyanReachData, []string{"Elihfoirl", "0505", "ACS", "A553236-D", "Ni Lo Po Ht", "", "Hierate", "G", "I", "Nora'a"})
	troyanReachData = append(troyanReachData, []string{"Ewoiftoil", "0204", "", "B546646-A", "Ni Ag", "", "Hierate", "", "I", "Nora'a"})
	troyanReachData = append(troyanReachData, []string{"Ftaleirl", "0508", "", "B53038A-8", "De Lo Ni Po", "", "Hierate", "", "I", "Nora'a"})
	troyanReachData = append(troyanReachData, []string{"H’a", "0207", "", "D657449-6", "Ni", "", "Hierate", "G", "I", "Nora'a"})
	troyanReachData = append(troyanReachData, []string{"Hkaha", "0309", "", "B897696-A", "Ag Ni", "", "Hierate", "G", "I", "Nora'a"})
	troyanReachData = append(troyanReachData, []string{"Hreahrya", "0209", "ACS", "B433A79-D", "Hi Na Po Ht", "", "Hierate", "G", "I", "Nora'a"})
	troyanReachData = append(troyanReachData, []string{"Iryao", "0302", "", "A5588B8-C", "Ht", "", "Hierate", "G", "I", "Nora'a"})
	troyanReachData = append(troyanReachData, []string{"Khi", "0420", "ACS", "B987588-B", "Ag Ni Ht", "", "Hierate", "G", "I", "Nora'a"})
	troyanReachData = append(troyanReachData, []string{"Khteiatloilr", "0203", "ACS", "B423456-C", "Ni Po Ht", "", "Hierate", "G", "I", "Nora'a"})
	troyanReachData = append(troyanReachData, []string{"Khtyekt", "0405", "ACS", "B200655-9", "Va Ni Na", "", "Hierate", "G", "I", "Nora'a"})
	troyanReachData = append(troyanReachData, []string{"Lafkin", "0704", "", "C77A846-9", "Wa", "", "Florian League", "G", "I", "Nora'a"})
	troyanReachData = append(troyanReachData, []string{"Nora’a", "0301", "", "A585645-9", "Ag Ni Ri", "", "Florian League", "", "I", "Nora'a"})
	troyanReachData = append(troyanReachData, []string{"Oiauh", "0110", "", "B1018B8-D", "Na Ic Va Ht", "", "Hierate", "", "I", "Nora'a"})
	troyanReachData = append(troyanReachData, []string{"Oihyeti’he", "0509", "AIC", "B779775-B", "Ht", "", "Hierate", "G", "I", "Nora'a"})
	troyanReachData = append(troyanReachData, []string{"Osototail", "0406", "", "E550857-7", "De Po Ht", "", "Hierate", "G", "I", "Nora'a"})
	troyanReachData = append(troyanReachData, []string{"Sei’eal", "0608", "", "B510886-B", "Na", "", "Hierate", "", "I", "Nora'a"})
	troyanReachData = append(troyanReachData, []string{"Souftea", "0500", "ACS", "A551754-D", "Po Ht", "", "Hierate", "G", "I", "Nora'a"})
	troyanReachData = append(troyanReachData, []string{"Suiaoir", "0308", "", "B651367-B", "Ni Po Lo Ht", "", "Hierate", "G", "I", "Nora'a"})
	troyanReachData = append(troyanReachData, []string{"Tanar", "0702", "", "C787640-8", "Ri Ag Ni An", "", "Florian League", "", "I", "Nora'a"})
	troyanReachData = append(troyanReachData, []string{"Tyea’ih", "0109", "", "B548889-A", "Ht", "", "Hierate", "", "I", "Nora'a"})
	troyanReachData = append(troyanReachData, []string{"Uao", "0709", "ACS", "C6A2456-8", "Fl Ni", "", "Hierate", "G", "I", "Nora'a"})
	troyanReachData = append(troyanReachData, []string{"Vadada", "0503", "N", "A410944-E", "Hi Na In Ht", "", "Florian League", "G", "I", "Nora'a"})
	troyanReachData = append(troyanReachData, []string{"Woilreawau", "0707", "ACS", "B100855-E", "Va Na Ht", "", "Hierate", "G", "I", "Nora'a"})
	troyanReachData = append(troyanReachData, []string{"Yaeawaokh", "0804", "ACS", "B43078B-C", "De Na Po Ht", "", "Hierate", "", "I", "Nora'a"})
	//GOERTAL J
	troyanReachData = append(troyanReachData, []string{"A’eouya", "0710", "", "E550000-0", "Ba", "", "", "G", "J", "Goertal"})
	troyanReachData = append(troyanReachData, []string{"Akhwohkyal", "0801", "", "BA95688-9", "Ag Ni An", "", "", "G", "J", "Goertal"})
	troyanReachData = append(troyanReachData, []string{"Alr", "0109", "", "A779548-B", "Ni", "", "Glorious Empire", "G", "J", "Goertal"})
	troyanReachData = append(troyanReachData, []string{"Asyuh", "0301", "ACS", "B8C3225-9", "Lo Fl Ni", "", "Glorious Empire", "G", "J", "Goertal"})
	troyanReachData = append(troyanReachData, []string{"Colony Six", "0401", "", "A68A541-D", "Wa Ni Ht", "", "", "G", "J", "Goertal"})
	troyanReachData = append(troyanReachData, []string{"Eauhti", "0810", "ACS", "B540489-B", "De Ni Po Ht", "", "", "G", "J", "Goertal"})
	troyanReachData = append(troyanReachData, []string{"Ehrafou", "0110", "ACS", "B00075A-E", "As Na Ht", "", "Hierate", "G", "J", "Goertal"})
	troyanReachData = append(troyanReachData, []string{"Eiaihiy", "0206", "ACS", "B500132-B", "Lo Ni Va", "", "Glorious Empire", "G", "J", "Goertal"})
	troyanReachData = append(troyanReachData, []string{"Eikhaaw", "0308", "", "C88978C-9", "Ri", "A", "Glorious Empire", "G", "J", "Goertal"})
	troyanReachData = append(troyanReachData, []string{"Eilaeah", "0504", "", "B863267-B", "Lo Ni Ht", "", "Hierate", "G", "J", "Goertal"})
	troyanReachData = append(troyanReachData, []string{"Erasaso", "0410", "AIC", "B68A136-C", "Lo Ni Wa Ht", "", "Hierate", "G", "J", "Goertal"})
	troyanReachData = append(troyanReachData, []string{"Fiyleakh", "0609", "ACS", "B41389A-C", "Ic Na Ht", "", "Hierate", "G", "J", "Goertal"})
	troyanReachData = append(troyanReachData, []string{"Ftiys", "0806", "ACS", "C76A325-7", "Lo Wa Ni", "", "", "G", "J", "Goertal"})
	troyanReachData = append(troyanReachData, []string{"Ftulrois", "0202", "", "B56866A-9", "Ag Ni Ri", "", "Glorious Empire", "", "J", "Goertal"})
	troyanReachData = append(troyanReachData, []string{"Goertel", "0402", "", "B6688DC-6", "", "A", "", "G", "J", "Goertal"})
	troyanReachData = append(troyanReachData, []string{"Hea’a", "0205", "", "E54026A-5", "Lo Ni De Po Lt", "", "Glorious Empire", "G", "J", "Goertal"})
	troyanReachData = append(troyanReachData, []string{"Hliyh", "0503", "ACS", "B200AB7-E", "Va Na Hi In Ht", "", "Hierate", "G", "J", "Goertal"})
	troyanReachData = append(troyanReachData, []string{"Hrahraiu", "0502", "ACS", "B42068C-C", "De Na Po Ni Ht", "A", "Hierate", "", "J", "Goertal"})
	troyanReachData = append(troyanReachData, []string{"Hteakya", "0403", "", "B423426-D", "Ni Po Ht", "", "Hierate", "G", "J", "Goertal"})
	troyanReachData = append(troyanReachData, []string{"Htourlao", "0208", "ACS", "B311978-E", "Ic Na In Hi Ht", "", "Glorious Empire", "G", "J", "Goertal"})
	troyanReachData = append(troyanReachData, []string{"Keawoaw", "0210", "", "B430433-9", "De Po Ni", "", "Glorious Empire", "G", "J", "Goertal"})
	troyanReachData = append(troyanReachData, []string{"Khau", "0406", "", "C687598-9", "Ag Ni Ht", "", "Hierate", "G", "J", "Goertal"})
	troyanReachData = append(troyanReachData, []string{"Oatre", "0203", "ACS", "B532336-C", "Lo Ni Po Ht", "", "Glorious Empire", "G", "J", "Goertal"})
	troyanReachData = append(troyanReachData, []string{"Oihu", "0306", "ACS", "B300454-9", "Va Ni", "", "Glorious Empire", "G", "J", "Goertal"})
	troyanReachData = append(troyanReachData, []string{"Syoakh", "0207", "ACS", "A6968BC-C", "Ht", "A", "Glorious Empire", "", "J", "Goertal"})
	troyanReachData = append(troyanReachData, []string{"Tryaoke", "0704", "", "D556978-8", "Hi Lt", "", "Hierate", "G", "J", "Goertal"})
	troyanReachData = append(troyanReachData, []string{"Yero’ilra", "0304", "", "D500897-7", "Va Na", "", "Glorious Empire", "G", "J", "Goertal"})
	troyanReachData = append(troyanReachData, []string{"Yestahwye", "0606", "AIC", "B9A4656-C", "De Ni Ht", "", "Hierate", "G", "J", "Goertal"})
	//TLAIOWAHA K
	troyanReachData = append(troyanReachData, []string{"Akoaft", "0610", "", "E898000-0", "Ba", "", "Hierate", "G", "K", "Tlaiowaha"})
	troyanReachData = append(troyanReachData, []string{"Asim", "0503", "", "B867564-6", "Ag Ni", "", "Kingdom of Drinax", "G", "K", "Tlaiowaha"})
	troyanReachData = append(troyanReachData, []string{"Asoieteal", "0108", "ACS", "B697688-A", "Ag Ni", "", "Hierate", "G", "K", "Tlaiowaha"})
	troyanReachData = append(troyanReachData, []string{"Blue", "0801", "", "B543487-B", "Po Ni Ht", "", "", "G", "K", "Tlaiowaha"})
	troyanReachData = append(troyanReachData, []string{"Camoran", "0203", "", "A55167A-B", "Ni Po", "", "Hierate", "G", "K", "Tlaiowaha"})
	troyanReachData = append(troyanReachData, []string{"Clarke", "0702", "", "B899753-8", "", "", "", "", "K", "Tlaiowaha"})
	troyanReachData = append(troyanReachData, []string{"Drinax", "0603", "", "A43645A-E", "Ni Ht", "", "Kingdom of Drinax", "G", "K", "Tlaiowaha"})
	troyanReachData = append(troyanReachData, []string{"Fantasy", "0808", "", "E788400-3", "Ni Lt", "", "", "G", "K", "Tlaiowaha"})
	troyanReachData = append(troyanReachData, []string{"Hilfer", "0804", "", "B55077A-6", "De Po", "", "", "", "K", "Tlaiowaha"})
	troyanReachData = append(troyanReachData, []string{"Hleakhayes", "0609", "", "E54348B-7", "Po Ni", "", "Hierate", "G", "K", "Tlaiowaha"})
	troyanReachData = append(troyanReachData, []string{"Iroioah", "0607", "", "B530113-C", "De Po Ni Lo Ht", "", "Hierate", "G", "K", "Tlaiowaha"})
	troyanReachData = append(troyanReachData, []string{"Keaih", "0210", "", "CAA5887-9", "Fl", "", "Hierate", "G", "K", "Tlaiowaha"})
	troyanReachData = append(troyanReachData, []string{"Khusai", "0403", "ACS", "A576655-C", "Ag Ni Ht", "", "Hierate", "G", "K", "Tlaiowaha"})
	troyanReachData = append(troyanReachData, []string{"Kteiroa", "0505", "AIC", "C560164-8", "De Lo Ni", "", "Hierate", "", "K", "Tlaiowaha"})
	troyanReachData = append(troyanReachData, []string{"Ohaualr", "0307", "ACS", "B422388-B", "Po Ni Lo", "", "Hierate", "G", "K", "Tlaiowaha"})
	troyanReachData = append(troyanReachData, []string{"Oiwoiieaw", "0103", "", "B787897-A", "Ri Ht", "", "Hierate", "G", "K", "Tlaiowaha"})
	troyanReachData = append(troyanReachData, []string{"Paal", "0805", "", "B564679-6", "Ag Ni Ri", "", "", "G", "K", "Tlaiowaha"})
	troyanReachData = append(troyanReachData, []string{"Pourne", "0704", "", "A9B2887-A", "Fl", "", "", "G", "K", "Tlaiowaha"})
	troyanReachData = append(troyanReachData, []string{"Sink", "0806", "", "D665220-5", "Ni Lo Lt", "", "", "G", "K", "Tlaiowaha"})
	troyanReachData = append(troyanReachData, []string{"Staha", "0409", "ACS", "B755486-B", "Ni Ht", "", "Hierate", "G", "K", "Tlaiowaha"})
	troyanReachData = append(troyanReachData, []string{"The World", "0707", "", "E100551-7", "In Ni Va", "", "", "G", "K", "Tlaiowaha"})
	troyanReachData = append(troyanReachData, []string{"Tlaiowaha", "0308", "ACS", "B420954-E", "De Hi In Na Po Ht", "", "Hierate", "G", "K", "Tlaiowaha"})
	troyanReachData = append(troyanReachData, []string{"Torpol", "0601", "", "B55A77A-B", "Wa", "", "", "G", "K", "Tlaiowaha"})
	troyanReachData = append(troyanReachData, []string{"Tyokh", "0606", "ACF", "B566A77-E", "Hi Ht", "", "Hierate", "G", "K", "Tlaiowaha"})
	troyanReachData = append(troyanReachData, []string{"Vorito", "0709", "", "E595ABB-A", "In Hi", "A", "Imperium Client State", "G", "K", "Tlaiowaha"})
	//BORDERLAND L
	troyanReachData = append(troyanReachData, []string{"Acrid", "0302", "", "AAC1388-D", "Fl Lo Ni Ht", "", "", "G", "L", "Borderland"})
	troyanReachData = append(troyanReachData, []string{"Argona", "0503", "", "B612586-9", "Ic Ni", "", "", "G", "L", "Borderland"})
	troyanReachData = append(troyanReachData, []string{"Arunisiir", "0201", "", "B776530-6", "Ag Ni", "", "", "G", "L", "Borderland"})
	troyanReachData = append(troyanReachData, []string{"Browne", "0610", "", "B550A96-9", "De Hi In Po", "", "", "G", "L", "Borderland"})
	troyanReachData = append(troyanReachData, []string{"Byrni", "0107", "", "B955699-6", "Ag Ni", "", "", "G", "L", "Borderland"})
	troyanReachData = append(troyanReachData, []string{"Cordan", "0401", "", "A895347-9", "Ni Lo", "", "", "G", "L", "Borderland"})
	troyanReachData = append(troyanReachData, []string{"Ergo", "0205", "", "X767500-3", "Ag Ni Lt", "R", "", "G", "L", "Borderland"})
	troyanReachData = append(troyanReachData, []string{"Exe", "0403", "", "B300101-A", "Ni Va Lo", "", "", "G", "L", "Borderland"})
	troyanReachData = append(troyanReachData, []string{"Falcon", "0305", "", "A558448-D", "Ni Ht", "", "", "G", "L", "Borderland"})
	troyanReachData = append(troyanReachData, []string{"Inurin", "0304", "", "E668776-5", "Ag Ri Lt", "", "", "G", "L", "Borderland"})
	troyanReachData = append(troyanReachData, []string{"Sperle", "0404", "", "BA8A78A-7", "Ri Wa", "", "", "", "L", "Borderland"})
	troyanReachData = append(troyanReachData, []string{"Tanith", "0301", "", "A589342-B", "Ni Lo", "", "", "G", "L", "Borderland"})
	troyanReachData = append(troyanReachData, []string{"Tech-World", "0204", "", "A555154-E", "Ni Lo Ht", "", "", "", "L", "Borderland"})
	troyanReachData = append(troyanReachData, []string{"Umemii", "0501", "", "C521877-7", "Na Po", "", "", "G", "L", "Borderland"})
	troyanReachData = append(troyanReachData, []string{"Villane", "0609", "", "B100634-8", "Na Ni Va", "", "", "G", "L", "Borderland"})
	//RANIB M
	troyanReachData = append(troyanReachData, []string{"Aehahr", "0204", "ARS", "B100449-C", "Va Ni", "", "Hierate", "G", "M", "Ranib"})
	troyanReachData = append(troyanReachData, []string{"Aiyostea", "0308", "", "B20068B-9", "Va Ni Na", "", "Hierate", "G", "M", "Ranib"})
	troyanReachData = append(troyanReachData, []string{"Aohfeau", "0210", "", "B998784-A", "Ag", "", "Hierate", "", "M", "Ranib"})
	troyanReachData = append(troyanReachData, []string{"Awo", "0306", "", "C530366-A", "Lo De Ni Po", "", "Hierate", "G", "M", "Ranib"})
	troyanReachData = append(troyanReachData, []string{"Ealea", "0109", "", "B576587-9", "Ag Ni", "", "Hierate", "", "M", "Ranib"})
	troyanReachData = append(troyanReachData, []string{"Eaweiya", "0305", "ACS", "A5406B7-A", "De Ni Po", "", "Hierate", "", "M", "Ranib"})
	troyanReachData = append(troyanReachData, []string{"Ehearye", "0603", "ACS", "A588779-C", "Ag Ri", "", "Hierate", "", "M", "Ranib"})
	troyanReachData = append(troyanReachData, []string{"Eiwakh", "0708", "", "D200777-8", "Va Na", "", "Hierate", "", "M", "Ranib"})
	troyanReachData = append(troyanReachData, []string{"Elahkoi", "0104", "", "C568587-9", "Ag Ni", "", "Hierate", "G", "M", "Ranib"})
	troyanReachData = append(troyanReachData, []string{"Ftoakh", "0206", "", "E673A8C-A", "In Hi", "A", "Hierate", "", "M", "Ranib"})
	troyanReachData = append(troyanReachData, []string{"Ftyewirl", "0102", "ACS", "B55648A-B", "Ni", "", "Hierate", "", "M", "Ranib"})
	troyanReachData = append(troyanReachData, []string{"Hfa’yuweas", "0401", "", "B555388-B", "Lo Ni", "", "Hierate", "G", "M", "Ranib"})
	troyanReachData = append(troyanReachData, []string{"Hkakh", "0807", "ACS", "A424546-E", "Ni", "", "Hierate", "G", "M", "Ranib"})
	troyanReachData = append(troyanReachData, []string{"Hkeleiakh", "0709", "ACS", "E310000-0", "Ba Lo Ni", "", "Hierate", "G", "M", "Ranib"})
	troyanReachData = append(troyanReachData, []string{"Hkesuh", "0302", "ACS", "B9A4758-B", "De", "", "Hierate", "G", "M", "Ranib"})
	troyanReachData = append(troyanReachData, []string{"Iysewekh", "0600", "ACS", "A52058A-E", "De Ni Po", "", "Hierate", "G", "M", "Ranib"})
	troyanReachData = append(troyanReachData, []string{"Ohtae", "0809", "", "B665168-9", "Lo Ni", "", "Hierate", "G", "M", "Ranib"})
	troyanReachData = append(troyanReachData, []string{"Oseweheal", "0501", "ACS", "B79A647-C", "Wa Ni", "", "Hierate", "G", "M", "Ranib"})
	troyanReachData = append(troyanReachData, []string{"Stohyus", "0805", "ACS", "A567866-C", "Ri", "", "Hierate", "G", "M", "Ranib"})
	troyanReachData = append(troyanReachData, []string{"Teharl", "0506", "", "C654453-A", "Ni", "", "Hierate", "", "M", "Ranib"})
	troyanReachData = append(troyanReachData, []string{"Uaeakhea", "0504", "ACS", "B530389-8", "Lo De Ni Po An", "", "Hierate", "G", "M", "Ranib"})
	troyanReachData = append(troyanReachData, []string{"Uitasoayaw", "0810", "ACS", "B579687-9", "Ni", "", "Hierate", "G", "M", "Ranib"})
	troyanReachData = append(troyanReachData, []string{"Uiwuar", "0105", "", "B101115-E", "Lo Ic Ni Va", "Hierate", "", "G", "M", "Ranib"})
	troyanReachData = append(troyanReachData, []string{"Yekhtia", "0202", "", "B423376-B", "Lo Ni Po", "", "Hierate", "G", "M", "Ranib"})
	//SILRAAIHE N
	troyanReachData = append(troyanReachData, []string{"Aisaoawi", "0108", "", "EAC5000-0", "Ba Fl", "", "Hierate", "G", "N", "Silraaihe"})
	troyanReachData = append(troyanReachData, []string{"Aiuiktiyr", "0508", "", "E797449-7", "Ni", "", "Hierate", "G", "N", "Silraaihe"})
	troyanReachData = append(troyanReachData, []string{"Aiuite", "0804", "ACS", "B645747-A", "Ag Ht", "", "Hierate", "G", "N", "Silraaihe"})
	troyanReachData = append(troyanReachData, []string{"Aoiyras", "0405", "", "B54068C-9", "De Ni Po", "A", "Hierate", "G", "N", "Silraaihe"})
	troyanReachData = append(troyanReachData, []string{"Awaweaw", "0807", "", "E855859-7", "", "", "Hierate", "G", "N", "Silraaihe"})
	troyanReachData = append(troyanReachData, []string{"Earlyu", "0113", "ACS", "B989859-C", "Ri Ht", "", "Hierate", "G", "N", "Silraaihe"})
	troyanReachData = append(troyanReachData, []string{"Eateaw", "0504", "", "E423000-0", "Ba", "", "Hierate", "G", "N", "Silraaihe"})
	troyanReachData = append(troyanReachData, []string{"Eiyehwehakhea", "0204", "ACS", "B79A57B-B", "Wa Ni", "", "Hierate", "G", "N", "Silraaihe"})
	troyanReachData = append(troyanReachData, []string{"Eoiw", "0101", "ACS", "B430684-C", "De Na Ni Po Ht An", "", "Hierate", "G", "N", "Silraaihe"}) //возможна не точность
	troyanReachData = append(troyanReachData, []string{"Ewyeyal", "0106", "ACS", "B58457A-B", "Ag Ni Ht", "", "Hierate", "", "N", "Silraaihe"})
	troyanReachData = append(troyanReachData, []string{"Haealroiea", "0206", "ACS", "B554487-9", "Ni", "", "Hierate", "", "N", "Silraaihe"})
	troyanReachData = append(troyanReachData, []string{"Hkuikhekh", "0104", "", "B532316-C", "Lo Ni Po Ht", "", "Hierate", "G", "N", "Silraaihe"})
	troyanReachData = append(troyanReachData, []string{"Htoihfui", "0509", "ACS", "A568873-C", "Ri Ht", "", "Hierate", "G", "N", "Silraaihe"})
	troyanReachData = append(troyanReachData, []string{"Huaholr", "0606", "ACS", "B42049C-9", "De Ni Po", "A", "Hierate", "G", "N", "Silraaihe"})
	troyanReachData = append(troyanReachData, []string{"Irlaiw", "0406", "ACF", "C436A75-D", "Hi Ht", "", "Hierate", "G", "N", "Silraaihe"})
	troyanReachData = append(troyanReachData, []string{"Kheiyyo", "0707", "", "C5257B7-9", "", "", "Hierate", "G", "N", "Silraaihe"})
	troyanReachData = append(troyanReachData, []string{"Ouiyloi", "0603", "", "C574789-8", "Ag Ht", "", "Hierate", "G", "N", "Silraaihe"})
	troyanReachData = append(troyanReachData, []string{"Rileakh", "0503", "", "C437855-A", "", "", "Hierate", "G", "N", "Silraaihe"})
	troyanReachData = append(troyanReachData, []string{"Sosuasaoh", "0705", "ACS", "B100858-B", "Va Na", "", "Hierate", "G", "N", "Silraaihe"})
	troyanReachData = append(troyanReachData, []string{"Stehasu", "0704", "ACS", "A520677-C", "De Na Ni Po Ht", "", "Hierate", "", "N", "Silraaihe"})
	troyanReachData = append(troyanReachData, []string{"Teiseirle", "0608", "", "BA9A377-8", "Lo Wa Ni", "", "Hierate", "G", "N", "Silraaihe"})
	troyanReachData = append(troyanReachData, []string{"Wuaki", "0208", "ACS", "A310545-C", "Ni Ht", "", "Hierate", "G", "N", "Silraaihe"})
	troyanReachData = append(troyanReachData, []string{"Yai’ilrao", "0801", "", "B85836B-B", "Lo Ni Ht", "", "Hierate", "G", "N", "Silraaihe"})
	troyanReachData = append(troyanReachData, []string{"Yu’eal", "0505", "ACS", "B432686-C", "Na Ni Po Ht", "", "Hierate", "G", "N", "Silraaihe"})
	//HKEA’AS O
	troyanReachData = append(troyanReachData, []string{"Afeakter", "0205", "ACS", "A69A68A-B", "Wa Ni", "", "Hierate", "G", "O", "Hkea'as"})
	troyanReachData = append(troyanReachData, []string{"Airliweiw", "0504", "", "D56767B-6", "Ag Ni Ri", "", "Hierate", "G", "O", "Hkea'as"})
	troyanReachData = append(troyanReachData, []string{"Aiwewakh", "0103", "", "BA961G3-D", "Lo Ni Ht", "", "Hierate", "G", "O", "Hkea'as"})
	troyanReachData = append(troyanReachData, []string{"Ayayo", "0105", "ARS", "B000674-D", "Ni As Na An Ht", "", "Hierate", "", "O", "Hkea'as"})
	troyanReachData = append(troyanReachData, []string{"Burgess", "0702", "", "B796633-6", "Ni Ag", "", "", "G", "O", "Hkea'as"})
	troyanReachData = append(troyanReachData, []string{"Eaohfose", "0603", "ACS", "B6736A7-A", "Ni", "", "Hierate", "G", "O", "Hkea'as"})
	troyanReachData = append(troyanReachData, []string{"Ereah", "0303", "", "B67A369-D", "Wa Lo Ni Ht", "", "Hierate", "G", "O", "Hkea'as"})
	troyanReachData = append(troyanReachData, []string{"Feaheaha", "0106", "", "E301268-9", "Ic Lo Ni Va", "", "Hierate", "", "O", "Hkea'as"})
	troyanReachData = append(troyanReachData, []string{"Gikarlum", "0604", "", "B310587-9", "Ni", "", "", "G", "O", "Hkea'as"})
	troyanReachData = append(troyanReachData, []string{"Hewekho", "0503", "", "E10079A-7", "Va Na", "", "Hierate", "G", "O", "Hkea'as"})
	troyanReachData = append(troyanReachData, []string{"Khtiyrlo", "0602", "ACS", "DA887CA-6", "Ag Ri", "A", "Hierate", "G", "O", "Hkea'as"})
	troyanReachData = append(troyanReachData, []string{"Ohraihah", "0104", "", "E8B6787-8", "Fl", "", "Hierate", "G", "O", "Hkea'as"})
	troyanReachData = append(troyanReachData, []string{"Ralaiw", "0301", "", "B420534-D", "Ni Po De Ht", "", "Hierate", "G", "O", "Hkea'as"})
	troyanReachData = append(troyanReachData, []string{"Tisilli", "0507", "", "B78A945-A", "Wa Hi", "", "", "G", "O", "Hkea'as"})
	troyanReachData = append(troyanReachData, []string{"Wesiyeah", "0101", "", "D641259-8", "Lo Ni Po", "", "Hierate", "G", "O", "Hkea'as"})
	//BINARY P
	troyanReachData = append(troyanReachData, []string{"Auitawry", "0710", "IRS N", "A56689A-C", "Ri Na", "A", "", "G", "P", "Binary"})
	troyanReachData = append(troyanReachData, []string{"Sarage", "0508", "N R", "B540523-B", "De Ni Po", "", "Imperium Client State", "G", "P", "Binary"})
}

func TroyanReachData() [][]string {
	return troyanReachData
}

func Test() {
	dataMap := make(map[string]int)
	for _, v := range troyanReachData {
		//fmt.Println(i, v)
		dataMap[v[4]]++
		//fmt.Println(len(v))
		if v[4] == "" {
			//fmt.Println(v, len(v))
		}
	}
	tcMap := make(map[string]int)
	for k, v := range dataMap {
		tc := strings.Split(k, " ")
		for i := range tc {
			tcMap[tc[i]]++
			if tc[i] == "" {
				fmt.Println(tc[i], i, k, v)
				fmt.Println(tc[i], i, k, v)
			}
		}
		//fmt.Println(k, v)

	}
	for k, v := range tcMap {
		fmt.Println(k, v)
	}
}
