package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
	"os"
	"strconv"
	"strings"
)

func main() {
	PullOtuData()
}

//PullOtuData -
func PullOtuData() {
	//worlddata := []string{}
	var worldString string
	var client http.Client
	f, err := os.Create("data.txt")
	if err != nil {
		fmt.Println(err)
		return
	}
	var worldLink string
	allSectors()
	totalSectors := len(allSectors())
	for i, val := range allSectors() {
		fmt.Println(val, "start")
		resp, err := client.Get(val)
		if err != nil {
			log.Fatal(err)
		}
		defer resp.Body.Close()

		if resp.StatusCode == http.StatusOK {
			bodyBytes, err := ioutil.ReadAll(resp.Body)
			if err != nil {
				log.Fatal(err)
			}
			bodyString := string(bodyBytes)
			fmt.Println(bodyString)
			lines := strings.Split(bodyString, "\n")
			for _, line := range lines {
				for _, hex := range allHexes() {

					if strings.Contains(line, hex+" ") {
						worldLink = val + "/" + hex
						fmt.Println("worldLink", worldLink)
						data, err := client.Get(worldLink)
						if err != nil {
							log.Fatal(err)
						}
						defer data.Body.Close()
						if data.StatusCode == http.StatusOK {
							fmt.Println(line)
							worldBytes, err := ioutil.ReadAll(data.Body)
							if err != nil {
								log.Fatal(err)
							}
							worldString = string(worldBytes)
							fmt.Println(worldString + "\n")
							l, err := f.WriteString(worldString + "\n")
							if err != nil {
								fmt.Println(err)
								f.Close()
								return
							}
							fmt.Printf("%v bytes written successfully from [%v]\n", l, worldLink)
							//time.Sleep(time.Millisecond * 86)
						}
					}
				}
			}
			//log.Info(bodyString)
			//fmt.Println(worldString)

			// l, err := f.WriteString(bodyString)
			// if err != nil {
			// 	fmt.Println(err)
			// 	f.Close()
			// 	return
			// }
			// fmt.Println(l, "bytes written successfully")

		} else {
			fmt.Println(resp.StatusCode, val)
		}
		fmt.Println("Pulled", i, "sectors of", totalSectors)
	}
	err = f.Close()
	if err != nil {
		fmt.Println(err)
		return
	}
	// lines := utils.LinesFromTXT("data.txt")
	// fmt.Println(lines)
	// for i, val := range lines {
	// 	fmt.Println("Check entry", i)
	// 	fmt.Println(val)
	// 	val = strings.ReplaceAll(val, "’", "'")

	// 	if val != "Sector	SS	Hex	Name	UWP	Bases	Remarks	Zone	PBG	Allegiance	Stars	{Ix}	(Ex)	[Cx]	Nobility	W	RU" {
	// 		utils.AddLineToFile("dataClean.txt", val)
	// 	}
	// }
	// fmt.Println("Formatting...")
	// linesC := utils.LinesFromTXT("dataClean.txt")
	// //Sector	SS	Hex	Name	UWP	Bases	Remarks	Zone	PBG	Allegiance	Stars	{Ix}	(Ex)	[Cx]	Nobility	W	RU
	// mapLen := make(map[int]int)
	// mapLen[0] = 6
	// mapLen[1] = 2
	// mapLen[2] = 4
	// mapLen[3] = 28
	// mapLen[4] = 9
	// mapLen[5] = 5
	// mapLen[6] = 44
	// mapLen[7] = 4
	// mapLen[8] = 3
	// mapLen[9] = 10
	// mapLen[10] = 29
	// mapLen[11] = 7
	// mapLen[12] = 7
	// mapLen[13] = 6
	// mapLen[14] = 8
	// mapLen[15] = 2
	// mapLen[16] = 5
	// total := len(lines)
	// for i, val := range linesC {

	// 	if i == 1 {
	// 		template := []string{}
	// 		for col := 0; col < 17; col++ {
	// 			template = append(template, "-")
	// 			for len(template[col]) < mapLen[col] {
	// 				template[col] += "-"
	// 			}

	// 		}
	// 		tempF := strings.Join(template, " ")
	// 		utils.AddLineToFile("dataFormatted.txt", tempF)
	// 	}
	// 	data := strings.Split(val, "	")
	// 	//fmt.Print("Formatting Line ", i)
	// 	for col := 0; col < 17; col++ {
	// 		// if mapLen[col] < len(data[col]) {
	// 		// 	mapLen[col] = len(data[col])
	// 		// }
	// 		// fmt.Print(mapLen[col], " ")
	// 		// sum += mapLen[col]
	// 		for len(data[col]) < mapLen[col] {
	// 			data[col] += " "
	// 			//		fmt.Print(".")
	// 		}
	// 	}
	// 	dataF := strings.Join(data, " ")
	// 	utils.AddLineToFile("dataFormatted.txt", dataF)
	// 	//fmt.Print("ok\n")
	// 	//fmt.Println(dataF)
	// 	fmt.Print(i, " of ", total, " complete\r")
	// }
	//6 2 4 28 9 5 44 4 3 10 29 7 7 6 8 2 5  - Line 66191 - max len(line):179
}

func allSectors() []string {
	return []string{
		"https://travellermap.com/data/Caesillian/tab",
		// "https://travellermap.com/data/Chtierabl/tab",
		// "https://travellermap.com/data/Stinj%20Tianz/tab",
		// "https://travellermap.com/data/Bliardlie/tab",
		// "https://travellermap.com/data/Zhiensh/tab",
		// "https://travellermap.com/data/Savria/tab",
		// "https://travellermap.com/data/Datsatl/tab",
		// "https://travellermap.com/data/Gakghang/tab",
		// "https://travellermap.com/data/Thaku%20Fung/tab",
		// "https://travellermap.com/data/Rzakki/tab",
		// "https://travellermap.com/data/Listanaya/tab",
		// "https://travellermap.com/data/Veg%20Fergakh/tab",
		// "https://travellermap.com/data/Dfotseth/tab",
		// "https://travellermap.com/data/Irugangog/tab",
		// "https://travellermap.com/data/Finggvakhou/tab",
		// "https://travellermap.com/data/Zortakh/tab",
		// "https://travellermap.com/data/Spangele/tab",
		// "https://travellermap.com/data/Nadir/tab",
		// "https://travellermap.com/data/Harbinger/tab",
		// "https://travellermap.com/data/Extremus/tab",
		// "https://travellermap.com/data/Viajlefliez/tab",
		// "https://travellermap.com/data/Bleblqansh/tab",
		// "https://travellermap.com/data/Driasera/tab",
		// "https://travellermap.com/data/Dalchie%20Jdatl/tab",
		// "https://travellermap.com/data/Chit%20Botshti/tab",
		// "https://travellermap.com/data/Ghoekhnael/tab",
		// "https://travellermap.com/data/Ksinanirz/tab",
		// "https://travellermap.com/data/Zao%20Kfeng%20Ig%20Grilokh/tab",
		// "https://travellermap.com/data/Knaeleng/tab",
		// "https://travellermap.com/data/Kharrthon/tab",
		// "https://travellermap.com/data/Oeghz%20Vaerrghr/tab",
		// "https://travellermap.com/data/Kfazz%20Ghik/tab",
		// "https://travellermap.com/data/Angfutsag/tab",
		// "https://travellermap.com/data/Rfigh/tab",
		// "https://travellermap.com/data/Tar'G'kell'p/tab",
		// "https://travellermap.com/data/Kteex!/tab",
		// "https://travellermap.com/data/Koog/tab",
		// "https://travellermap.com/data/Xeeleer/tab",
		// "https://travellermap.com/data/Unthaank/tab",
		// "https://travellermap.com/data/Brieplanz/tab",
		// "https://travellermap.com/data/Sidiadl/tab",
		// "https://travellermap.com/data/Zdiedeiant/tab",
		// "https://travellermap.com/data/Stiatlchepr/tab",
		// "https://travellermap.com/data/Itvikiastaf/tab",
		// "https://travellermap.com/data/Knoellighz/tab",
		// "https://travellermap.com/data/Dhuerorrg/tab",
		// "https://travellermap.com/data/Ngathksirz/tab",
		// "https://travellermap.com/data/Fa%20Dzaets/tab",
		// "https://travellermap.com/data/Gzaekfueg/tab",
		// "https://travellermap.com/data/Gashikan/tab",
		// "https://travellermap.com/data/Trenchans/tab",
		// "https://travellermap.com/data/Ktiin'gzat/tab",
		// "https://travellermap.com/data/Mugheen't/tab",
		// "https://travellermap.com/data/Grikr!ng/tab",
		// "https://travellermap.com/data/Ukaarriit!!b/tab",
		// "https://travellermap.com/data/Kring%20Noor/tab",
		// "https://travellermap.com/data/Mbil!!gh/tab",
		// "https://travellermap.com/data/Kweenexis/tab",
		// "https://travellermap.com/data/Pliabriebl/tab",
		// "https://travellermap.com/data/Eiaplial/tab",
		// "https://travellermap.com/data/Zhdant/tab",
		// "https://travellermap.com/data/Tienspevnekr/tab",
		// "https://travellermap.com/data/Ziafrplians/tab",
		// "https://travellermap.com/data/Gvurrdon/tab",
		// "https://travellermap.com/data/Tuglikki/tab",
		// "https://travellermap.com/data/Provence/tab",
		// "https://travellermap.com/data/Windhorn/tab",
		// "https://travellermap.com/data/Meshan/tab",
		// "https://travellermap.com/data/Mendan/tab",
		// "https://travellermap.com/data/Amdukan/tab",
		// "https://travellermap.com/data/Arzul/tab",
		// "https://travellermap.com/data/Gn'hk'r/tab",
		// "https://travellermap.com/data/Gur/tab",
		// "https://travellermap.com/data/Un'k!!k'ng/tab",
		// "https://travellermap.com/data/Xaagr/tab",
		// "https://travellermap.com/data/Eekrookrigz/tab",
		// "https://travellermap.com/data/Hoboreth/tab",
		// "https://travellermap.com/data/Tsadra%20Davr/tab",
		// "https://travellermap.com/data/Tsadra/tab",
		// "https://travellermap.com/data/Yiklerzdanzh/tab",
		// "https://travellermap.com/data/Far%20Frontiers/tab",
		// "https://travellermap.com/data/Foreven/tab",
		// "https://travellermap.com/data/Spinward%20Marches/tab",
		// "https://travellermap.com/data/Deneb/tab",
		// "https://travellermap.com/data/Corridor/tab",
		// "https://travellermap.com/data/Vland/tab",
		// "https://travellermap.com/data/Lishun/tab",
		// "https://travellermap.com/data/Antares/tab",
		// "https://travellermap.com/data/Empty%20Quarter/tab",
		// "https://travellermap.com/data/Star's%20End/tab",
		// "https://travellermap.com/data/Gh!hken/tab",
		// "https://travellermap.com/data/Ruupiin/tab",
		// "https://travellermap.com/data/Raakaan/tab",
		// "https://travellermap.com/data/Uuk/tab",
		// "https://travellermap.com/data/Gnaa%20Iimb'kr/tab",
		// "https://travellermap.com/data/Jiti/tab",
		// "https://travellermap.com/data/Chiep%20Zhez/tab",
		// "https://travellermap.com/data/Astron/tab",
		// "https://travellermap.com/data/Fulani/tab",
		// "https://travellermap.com/data/Vanguard%20Reaches/tab",
		// "https://travellermap.com/data/The%20Beyond/tab",
		// "https://travellermap.com/data/Trojan%20Reach/tab",
		// "https://travellermap.com/data/Reft/tab",
		// "https://travellermap.com/data/Gushemege/tab",
		// "https://travellermap.com/data/Dagudashaag/tab",
		// "https://travellermap.com/data/Core/tab",
		// "https://travellermap.com/data/Fornast/tab",
		// "https://travellermap.com/data/Ley/tab",
		// "https://travellermap.com/data/Gateway/tab",
		// "https://travellermap.com/data/Luretiir!girr/tab",
		// "https://travellermap.com/data/X'kug/tab",
		// "https://travellermap.com/data/Kilong/tab",
		// "https://travellermap.com/data/Bar'kakr/tab",
		// "https://travellermap.com/data/Mighabohk/tab",
		// "https://travellermap.com/data/Sing/tab",
		// "https://travellermap.com/data/Mavuzog/tab",
		// "https://travellermap.com/data/Theta%20Borealis/tab",
		// "https://travellermap.com/data/Theron/tab",
		// "https://travellermap.com/data/Iphigenaia/tab",
		// "https://travellermap.com/data/Touchstone/tab",
		// "https://travellermap.com/data/Riftspan%20Reaches/tab",
		// "https://travellermap.com/data/Verge/tab",
		// "https://travellermap.com/data/Ilelish/tab",
		// "https://travellermap.com/data/Zarushagar/tab",
		// "https://travellermap.com/data/Massilia/tab",
		// "https://travellermap.com/data/Delphi/tab",
		// "https://travellermap.com/data/Glimmerdrift%20Reaches/tab",
		// "https://travellermap.com/data/Crucis%20Margin/tab",
		// "https://travellermap.com/data/Kaa%20G!'kul/tab",
		// "https://travellermap.com/data/Gzirr!k'l/tab",
		// "https://travellermap.com/data/K'trekreer/tab",
		// "https://travellermap.com/data/Nuughe/tab",
		// "https://travellermap.com/data/N!!krumbiix/tab",
		// "https://travellermap.com/data/Uidlexna/tab",
		// "https://travellermap.com/data/Harea/tab",
		// "https://travellermap.com/data/Khaeaw/tab",
		// "https://travellermap.com/data/Faoheiroi'iyhao/tab",
		// "https://travellermap.com/data/Ftaoiyekyu/tab",
		// "https://travellermap.com/data/Afawahisa/tab",
		// "https://travellermap.com/data/Hlakhoi/tab",
		// "https://travellermap.com/data/Ealiyasiyw/tab",
		// "https://travellermap.com/data/Reaver's%20Deep/tab",
		// "https://travellermap.com/data/Daibei/tab",
		// "https://travellermap.com/data/Diaspora/tab",
		// "https://travellermap.com/data/Old%20Expanses/tab",
		// "https://travellermap.com/data/Hinterworlds/tab",
		// "https://travellermap.com/data/Leonidae/tab",
		// "https://travellermap.com/data/Extolian/tab",
		// "https://travellermap.com/data/Ricenden/tab",
		// "https://travellermap.com/data/Blaskon/tab",
		// "https://travellermap.com/data/Nooq/tab",
		// "https://travellermap.com/data/Gzektixk/tab",
		// "https://travellermap.com/data/Googalesh/tab",
		// "https://travellermap.com/data/Tlyasea/tab",
		// "https://travellermap.com/data/Hkakhaeaw/tab",
		// "https://travellermap.com/data/Esai'yo/tab",
		// "https://travellermap.com/data/Waroatahe/tab",
		// "https://travellermap.com/data/Karleaya/tab",
		// "https://travellermap.com/data/Staihaia'yo/tab",
		// "https://travellermap.com/data/Iwahfuah/tab",
		// "https://travellermap.com/data/Dark%20Nebula/tab",
		// "https://travellermap.com/data/Magyar/tab",
		// "https://travellermap.com/data/Solomani%20Rim/tab",
		// "https://travellermap.com/data/Alpha%20Crucis/tab",
		// "https://travellermap.com/data/Spica/tab",
		// "https://travellermap.com/data/Phlask/tab",
		// "https://travellermap.com/data/Centrax/tab",
		// "https://travellermap.com/data/Wrenton/tab",
		// "https://travellermap.com/data/Folgore/tab",
		// "https://travellermap.com/data/Avereguar/tab",
		// "https://travellermap.com/data/Kolire/tab",
		// "https://travellermap.com/data/Taezohm/tab",
		// "https://travellermap.com/data/Khuaryakh/tab",
		// "https://travellermap.com/data/Yahehwe/tab",
		// "https://travellermap.com/data/Kefiykhta/tab",
		// "https://travellermap.com/data/Heakhafaw/tab",
		// "https://travellermap.com/data/Etakhasoa/tab",
		// "https://travellermap.com/data/Aktifao/tab",
		// "https://travellermap.com/data/Uistilrao/tab",
		// "https://travellermap.com/data/Ustral%20Quadrant/tab",
		// "https://travellermap.com/data/Canopus/tab",
		// "https://travellermap.com/data/Aldebaran/tab",
		// "https://travellermap.com/data/Neworld/tab",
		// "https://travellermap.com/data/Langere/tab",
		// "https://travellermap.com/data/Drakken/tab",
		// "https://travellermap.com/data/Lorspane/tab",
		// "https://travellermap.com/data/Porlock/tab",
		// "https://travellermap.com/data/Kidunal/tab",
		// "https://travellermap.com/data/Treece/tab",
		// "https://travellermap.com/data/Genfert/tab",
		// "https://travellermap.com/data/The%20Roast/tab",
		// "https://travellermap.com/data/Aftailr/tab",
		// "https://travellermap.com/data/Ohieraoi/tab",
		// "https://travellermap.com/data/Fahreahluis/tab",
		// "https://travellermap.com/data/Hfiywitir/tab",
		// "https://travellermap.com/data/Irlaftalea/tab",
		// "https://travellermap.com/data/Teahloarifu/tab",
		// "https://travellermap.com/data/Ahkiweahi'/tab",
		// "https://travellermap.com/data/Banners/tab",
		// "https://travellermap.com/data/Hanstone/tab",
		// "https://travellermap.com/data/Malorn/tab",
		// "https://travellermap.com/data/Hadji/tab",
		// "https://travellermap.com/data/Storr/tab",
		// "https://travellermap.com/data/Mikhail/tab",
		// "https://travellermap.com/data/Darret/tab",
		// "https://travellermap.com/data/Ataurre/tab",
		// "https://travellermap.com/data/Katoonah/tab",
		// "https://travellermap.com/data/Uytal/tab",
		// "https://travellermap.com/data/Sporelex/tab",
		// "https://travellermap.com/data/Olantar/tab",
		// "https://travellermap.com/data/Tahahroal/tab",
		// "https://travellermap.com/data/A'yosea/tab",
		// "https://travellermap.com/data/Usoirarloiau/tab",
		// "https://travellermap.com/data/Oiah/tab",
		// "https://travellermap.com/data/Eahyaw/tab",
		// "https://travellermap.com/data/Ftyer/tab",
		// "https://travellermap.com/data/Elyetleisiyea/tab",
		// "https://travellermap.com/data/Ahriman/tab",
		// "https://travellermap.com/data/Holowon/tab",
		// "https://travellermap.com/data/Amderstun/tab",
		// "https://travellermap.com/data/RimReach/tab",
		// "https://travellermap.com/data/Phlange/tab",
		// "https://travellermap.com/data/Tracerie/tab",
		// "https://travellermap.com/data/Wrence/tab",
		// "https://travellermap.com/data/Muarne/tab",
		// "https://travellermap.com/data/Lancask/tab",
		// "https://travellermap.com/data/Tensk/tab",
		// "https://travellermap.com/data/Aphlent/tab",
		// "https://travellermap.com/data/Randtred/tab",
		// "https://travellermap.com/data/Uroac/tab",
		// "https://travellermap.com/data/Iphl/tab",
		// "https://travellermap.com/data/Qona/tab",
		// "https://travellermap.com/data/Qiask/tab",
		// "https://travellermap.com/data/Uaftdual/tab",
		// "https://travellermap.com/data/Orna/tab",
		// "https://travellermap.com/data/Noontask/tab",
		// "https://travellermap.com/data/Onoo/tab",
		// "https://travellermap.com/data/Dranon/tab",
		// "https://travellermap.com/data/Geerphli/tab",
		// "https://travellermap.com/data/Lila/tab",
		// "https://travellermap.com/data/Koirtrua/tab",
		// "https://travellermap.com/data/Ultret/tab",
		// "https://travellermap.com/data/Binaurie/tab",
		// "https://travellermap.com/data/Grevanne/tab",
		// "https://travellermap.com/data/Femengaal/tab",
		// "https://travellermap.com/data/Wobanna/tab",
		// "https://travellermap.com/data/Poinmaali/tab",
		// "https://travellermap.com/data/Hintrab/tab",
		// "https://travellermap.com/data/Ebollam/tab",
		// "https://travellermap.com/data/Tumluun/tab",
		// "https://travellermap.com/data/Yasktier/tab",
		// "https://travellermap.com/data/Uumpallu/tab",
		// "https://travellermap.com/data/Quavas/tab",
		// "https://travellermap.com/data/Indierri/tab",
		// "https://travellermap.com/data/Alila/tab",
		// "https://travellermap.com/data/Gudala/tab",
		// "https://travellermap.com/data/Giskakii/tab",
		// "https://travellermap.com/data/Incognita%20Ulterior/tab",
		// "https://travellermap.com/data/Coreward%20Shore/tab",
		// "https://travellermap.com/data/Greenwald's%20Beach/tab",
		// "https://travellermap.com/data/Narrow%20Transit/tab",
		// "https://travellermap.com/data/Sisyphus%20Ulterior/tab",
		// "https://travellermap.com/data/Pytheus%20Interior/tab",
		// "https://travellermap.com/data/Idirda/tab",
		// "https://travellermap.com/data/Kaalin%20Ulterior/tab",
		// "https://travellermap.com/data/Near%20Side%20of%20Yonder/tab",
		// "https://travellermap.com/data/Deepnight/tab",
		// "https://travellermap.com/data/Vilaakasii/tab",
		// "https://travellermap.com/data/Incognita%20Citerior/tab",
		// "https://travellermap.com/data/Central%20Bay/tab",
		// "https://travellermap.com/data/Far%20Shore%20of%20Yonder/tab",
		// "https://travellermap.com/data/Colaeus/tab",
		// "https://travellermap.com/data/Sisyphus%20Citerior/tab",
		// "https://travellermap.com/data/Pytheas/tab",
		// "https://travellermap.com/data/Diamond%20Scatter/tab",
		// "https://travellermap.com/data/Kaalin%20Citerior/tab",
		// "https://travellermap.com/data/First%20Prospect/tab",
		// "https://travellermap.com/data/Few%20Stars/tab",
		// "https://travellermap.com/data/No%20Shore/tab",
		// "https://travellermap.com/data/Big%20Empty/tab",
		// "https://travellermap.com/data/Open%20Rift/tab",
		// "https://travellermap.com/data/Last%20Prospect/tab",
		// "https://travellermap.com/data/Best%20Prospect/tab",
		// "https://travellermap.com/data/No%20Prospect/tab",
		// "https://travellermap.com/data/Black%20Night/tab",
		// "https://travellermap.com/data/Few%20Glimmers/tab",
		// "https://travellermap.com/data/Just%20Empty/tab",
		// "https://travellermap.com/data/Crossing/tab",
		// "https://travellermap.com/data/Far%20Shore/tab",
		// "https://travellermap.com/data/Far%20Shore%202/tab",
		// "https://travellermap.com/data/Annwn/tab",
		// "https://travellermap.com/data/Baltia/tab",
		// "https://travellermap.com/data/Brittia/tab",
		// "https://travellermap.com/data/Lemuria/tab",
		// "https://travellermap.com/data/Muspelheim/tab",
		// "https://travellermap.com/data/Hades/tab",
		// "https://travellermap.com/data/Harappa/tab",
		// "https://travellermap.com/data/Atlantis/tab",
		// "https://travellermap.com/data/Wilderlands/tab",
		// "https://travellermap.com/data/Ifingr/tab",
		// "https://travellermap.com/data/Styx/tab",
		// "https://travellermap.com/data/Tir%20NaNog/tab",
		// "https://travellermap.com/data/Olympus/tab",
		// "https://travellermap.com/data/Bifrost/tab",
		// "https://travellermap.com/data/Valhol/tab",
		// "https://travellermap.com/data/Hvergelmir/tab",
		// "https://travellermap.com/data/Acheron/tab",
		// "https://travellermap.com/data/Cathago/tab",
		// "https://travellermap.com/data/Arcadia/tab",
		// "https://travellermap.com/data/Troy/tab",
		// "https://travellermap.com/data/Gimli/tab",
		// "https://travellermap.com/data/Niflheim/tab",
		// "https://travellermap.com/data/Lethe/tab",
		// "https://travellermap.com/data/Hubur/tab",
		// "https://travellermap.com/data/Celadon/tab",
		// "https://travellermap.com/data/Naraka/tab",
		// "https://travellermap.com/data/Malvam/tab",
		// "https://travellermap.com/data/Elivagar/tab",
		// "https://travellermap.com/data/Riftsedge%20Coreward/tab",
		// "https://travellermap.com/data/Riftsedge%20Bridge/tab",
		// "https://travellermap.com/data/FSD%20Transition%20Spinward/tab",
		// "https://travellermap.com/data/LSD%20Transition%20One/tab",
		// "https://travellermap.com/data/ZSD%20Transition%20Two/tab",
		// "https://travellermap.com/data/LSD%20Transition%20Three/tab",
		// "https://travellermap.com/data/LSD%20Transition%20Four/tab",
		// "https://travellermap.com/data/LSD%20Transition%20Trailing/tab",
		// "https://travellermap.com/data/Big%20Island/tab",
		// "https://travellermap.com/data/Riftsedge%20Central/tab",
		// "https://travellermap.com/data/Voidshore%20One/tab",
		// "https://travellermap.com/data/Voidshore%20Two/tab",
		// "https://travellermap.com/data/Voidshore%20Three/tab",
		// "https://travellermap.com/data/LSD%20Transition%20Rimward/tab",
		// "https://travellermap.com/data/Voidshore%20Four/tab",
		// "https://travellermap.com/data/Voidshore%20Five/tab",
		// "https://travellermap.com/data/Voidshore%20Six/tab",
		// "https://travellermap.com/data/Voidshore%20Trailing/tab",
		// "https://travellermap.com/data/Riftsedge%20Rimward/tab",
		// "https://travellermap.com/data/VS-X/tab",
		// "https://travellermap.com/data/Voidshore%20Seven/tab",
		// "https://travellermap.com/data/Orion's%20Spit%20Coreward/tab",
		// "https://travellermap.com/data/Voidshore%20Eight/tab",
		// "https://travellermap.com/data/Voidshore%20Nine/tab",
		// "https://travellermap.com/data/Voidshore%20Ten/tab",
		// "https://travellermap.com/data/Voidshore%20Eleven/tab",
		// "https://travellermap.com/data/Voidshore%20Rimward/tab",
		// "https://travellermap.com/data/Orion's%20Spit%20Rimward/tab",
	}
}

func allSectors2() []string {
	return []string{
		"http://travellermap.com/data/Caesillian",
		"http://travellermap.com/data/Chtierabl",
		"http://travellermap.com/data/Stinj%20Tianz",
		"http://travellermap.com/data/Bliardlie",
		"http://travellermap.com/data/Zhiensh",
		"http://travellermap.com/data/Savria",
		"http://travellermap.com/data/Datsatl",
		"http://travellermap.com/data/Gakghang",
		"http://travellermap.com/data/Thaku%20Fung",
		"http://travellermap.com/data/Rzakki",
		"http://travellermap.com/data/Listanaya",
		"http://travellermap.com/data/Veg%20Fergakh",
		"http://travellermap.com/data/Dfotseth",
		"http://travellermap.com/data/Irugangog",
		"http://travellermap.com/data/Finggvakhou",
		"http://travellermap.com/data/Zortakh",
		"http://travellermap.com/data/Spangele",
		"http://travellermap.com/data/Nadir",
		"http://travellermap.com/data/Harbinger",
		"http://travellermap.com/data/Extremus",
		"http://travellermap.com/data/Viajlefliez",
		"http://travellermap.com/data/Bleblqansh",
		"http://travellermap.com/data/Driasera",
		"http://travellermap.com/data/Dalchie%20Jdatl",
		"http://travellermap.com/data/Chit%20Botshti",
		"http://travellermap.com/data/Ghoekhnael",
		"http://travellermap.com/data/Ksinanirz",
		"http://travellermap.com/data/Zao%20Kfeng%20Ig%20Grilokh",
		"http://travellermap.com/data/Knaeleng",
		"http://travellermap.com/data/Kharrthon",
		"http://travellermap.com/data/Oeghz%20Vaerrghr",
		"http://travellermap.com/data/Kfazz%20Ghik",
		"http://travellermap.com/data/Angfutsag",
		"http://travellermap.com/data/Rfigh",
		"http://travellermap.com/data/Tar'G'kell'p",
		"http://travellermap.com/data/Kteex",
		"http://travellermap.com/data/Koog",
		"http://travellermap.com/data/Xeeleer",
		"http://travellermap.com/data/Unthaank",
		"http://travellermap.com/data/Brieplanz",
		"http://travellermap.com/data/Sidiadl",
		"http://travellermap.com/data/Zdiedeiant",
		"http://travellermap.com/data/Stiatlchepr",
		"http://travellermap.com/data/Itvikiastaf",
		"http://travellermap.com/data/Knoellighz",
		"http://travellermap.com/data/Dhuerorrg",
		"http://travellermap.com/data/Ngathksirz",
		"http://travellermap.com/data/Fa%20Dzaets",
		"http://travellermap.com/data/Gzaekfueg",
		"http://travellermap.com/data/Gashikan",
		"http://travellermap.com/data/Trenchans",
		"http://travellermap.com/data/Ktiin'gzat",
		"http://travellermap.com/data/Mugheen't",
		"http://travellermap.com/data/Grikr!ng",
		"http://travellermap.com/data/Ukaarriit!!b",
		"http://travellermap.com/data/Kring%20Noor",
		"http://travellermap.com/data/Mbil!!gh",
		"http://travellermap.com/data/Kweenexis",
		"http://travellermap.com/data/Pliabriebl",
		"http://travellermap.com/data/Eiaplial",
		"http://travellermap.com/data/Zhdant",
		"http://travellermap.com/data/Tienspevnekr",
		"http://travellermap.com/data/Ziafrplians",
		"http://travellermap.com/data/Gvurrdon",
		"http://travellermap.com/data/Tuglikki",
		"http://travellermap.com/data/Provence",
		"http://travellermap.com/data/Windhorn",
		"http://travellermap.com/data/Meshan",
		"http://travellermap.com/data/Mendan",
		"http://travellermap.com/data/Amdukan",
		"http://travellermap.com/data/Arzul",
		"http://travellermap.com/data/Gn'hk'r",
		"http://travellermap.com/data/Gur",
		"http://travellermap.com/data/Un'k!!k'ng",
		"http://travellermap.com/data/Xaagr",
		"http://travellermap.com/data/Eekrookrigz",
		"http://travellermap.com/data/Hoboreth",
		"http://travellermap.com/data/Tsadra%20Davr",
		"http://travellermap.com/data/Tsadra",
		"http://travellermap.com/data/Yiklerzdanzh",
		"http://travellermap.com/data/Far%20Frontiers",
		"http://travellermap.com/data/Foreven",
		"http://travellermap.com/data/Spinward%20Marches",
		"http://travellermap.com/data/Deneb",
		"http://travellermap.com/data/Corridor",
		"http://travellermap.com/data/Vland",
		"http://travellermap.com/data/Lishun",
		"http://travellermap.com/data/Antares",
		"http://travellermap.com/data/Empty%20Quarter",
		"http://travellermap.com/data/Star's%20End",
		"http://travellermap.com/data/Gh!hken",
		"http://travellermap.com/data/Ruupiin",
		"http://travellermap.com/data/Raakaan",
		"http://travellermap.com/data/Uuk",
		"http://travellermap.com/data/Gnaa%20Iimb'kr",
		"http://travellermap.com/data/Jiti",
		"http://travellermap.com/data/Chiep%20Zhez",
		"http://travellermap.com/data/Astron",
		"http://travellermap.com/data/Fulani",
		"http://travellermap.com/data/Vanguard%20Reaches",
		"http://travellermap.com/data/The%20Beyond",
		"http://travellermap.com/data/Trojan%20Reach",
		"http://travellermap.com/data/Reft",
		"http://travellermap.com/data/Gushemege",
		"http://travellermap.com/data/Dagudashaag",
		"http://travellermap.com/data/Core",
		"http://travellermap.com/data/Fornast",
		"http://travellermap.com/data/Ley",
		"http://travellermap.com/data/Gateway",
		"http://travellermap.com/data/Luretiir!girr",
		"http://travellermap.com/data/X'kug",
		"http://travellermap.com/data/Kilong",
		"http://travellermap.com/data/Bar'kakr",
		"http://travellermap.com/data/Mighabohk",
		"http://travellermap.com/data/Sing",
		"http://travellermap.com/data/Mavuzog",
		"http://travellermap.com/data/Theta%20Borealis",
		"http://travellermap.com/data/Theron",
		"http://travellermap.com/data/Iphigenaia",
		"http://travellermap.com/data/Touchstone",
		"http://travellermap.com/data/Riftspan%20Reaches",
		"http://travellermap.com/data/Verge",
		"http://travellermap.com/data/Ilelish",
		"http://travellermap.com/data/Zarushagar",
		"http://travellermap.com/data/Massilia",
		"http://travellermap.com/data/Delphi",
		"http://travellermap.com/data/Glimmerdrift%20Reaches",
		"http://travellermap.com/data/Crucis%20Margin",
		"http://travellermap.com/data/Numbis",
		"http://travellermap.com/data/Gzirr!k'l",
		"http://travellermap.com/data/K'trekreer",
		"http://travellermap.com/data/Nuughe",
		"http://travellermap.com/data/N!!krumbiix",
		"http://travellermap.com/data/Uidlexna",
		"http://travellermap.com/data/Harea",
		"http://travellermap.com/data/Khaeaw",
		"http://travellermap.com/data/Faoheiroi'iyhao",
		"http://travellermap.com/data/Ftaoiyekyu",
		"http://travellermap.com/data/Afawahisa",
		"http://travellermap.com/data/Hlakhoi",
		"http://travellermap.com/data/Ealiyasiyw",
		"http://travellermap.com/data/Reaver's%20Deep",
		"http://travellermap.com/data/Daibei",
		"http://travellermap.com/data/Diaspora",
		"http://travellermap.com/data/Old%20Expanses",
		"http://travellermap.com/data/Hinterworlds",
		"http://travellermap.com/data/Leonidae",
		"http://travellermap.com/data/Extolian",
		"http://travellermap.com/data/Ricenden",
		"http://travellermap.com/data/Blaskon",
		"http://travellermap.com/data/Nooq",
		"http://travellermap.com/data/Gzektixk",
		"http://travellermap.com/data/Googalesh",
		"http://travellermap.com/data/Tlyasea",
		"http://travellermap.com/data/Hkakhaeaw",
		"http://travellermap.com/data/Esai'yo",
		"http://travellermap.com/data/Waroatahe",
		"http://travellermap.com/data/Karleaya",
		"http://travellermap.com/data/Staihaia'yo",
		"http://travellermap.com/data/Iwahfuah",
		"http://travellermap.com/data/Dark%20Nebula",
		"http://travellermap.com/data/Magyar",
		"http://travellermap.com/data/Solomani%20Rim",
		"http://travellermap.com/data/Alpha%20Crucis",
		"http://travellermap.com/data/Spica",
		"http://travellermap.com/data/Phlask",
		"http://travellermap.com/data/Centrax",
		"http://travellermap.com/data/Wrenton",
		"http://travellermap.com/data/Folgore",
		"http://travellermap.com/data/Avereguar",
		"http://travellermap.com/data/Kolire",
		"http://travellermap.com/data/Taezohm",
		"http://travellermap.com/data/Khuaryakh",
		"http://travellermap.com/data/Yahehwe",
		"http://travellermap.com/data/Kefiykhta",
		"http://travellermap.com/data/Heakhafaw",
		"http://travellermap.com/data/Etakhasoa",
		"http://travellermap.com/data/Aktifao",
		"http://travellermap.com/data/Uistilrao",
		"http://travellermap.com/data/Ustral%20Quadrant",
		"http://travellermap.com/data/Canopus",
		"http://travellermap.com/data/Aldebaran",
		"http://travellermap.com/data/Neworld",
		"http://travellermap.com/data/Langere",
		"http://travellermap.com/data/Drakken",
		"http://travellermap.com/data/Lorspane",
		"http://travellermap.com/data/Porlock",
		"http://travellermap.com/data/Kidunal",
		"http://travellermap.com/data/Treece",
		"http://travellermap.com/data/Genfert",
		"http://travellermap.com/data/The%20Roast",
		"http://travellermap.com/data/Aftailr",
		"http://travellermap.com/data/Ohieraoi",
		"http://travellermap.com/data/Fahreahluis",
		"http://travellermap.com/data/Hfiywitir",
		"http://travellermap.com/data/Irlaftalea",
		"http://travellermap.com/data/Teahloarifu",
		"http://travellermap.com/data/Ahkiweahi",
		"http://travellermap.com/data/Banners",
		"http://travellermap.com/data/Hanstone",
		"http://travellermap.com/data/Malorn",
		"http://travellermap.com/data/Hadji",
		"http://travellermap.com/data/Storr",
		"http://travellermap.com/data/Mikhail",
		"http://travellermap.com/data/Darret",
		"http://travellermap.com/data/Ataurre",
		"http://travellermap.com/data/Katoonah",
		"http://travellermap.com/data/Uytal",
		"http://travellermap.com/data/Sporelex",
		"http://travellermap.com/data/Olantar",
		"http://travellermap.com/data/Tahahroal",
		"http://travellermap.com/data/A'yosea",
		"http://travellermap.com/data/Usoirarloiau",
		"http://travellermap.com/data/Oiah",
		"http://travellermap.com/data/Eahyaw",
		"http://travellermap.com/data/Ftyer",
		"http://travellermap.com/data/Elyetleisiyea",
		"http://travellermap.com/data/Ahriman",
		"http://travellermap.com/data/Holowon",
		"http://travellermap.com/data/Amderstun",
		"http://travellermap.com/data/RimReach",
		"http://travellermap.com/data/Phlange",
		"http://travellermap.com/data/Tracerie",
		"http://travellermap.com/data/Wrence",
		"http://travellermap.com/data/Muarne",
		"http://travellermap.com/data/Lancask",
		"http://travellermap.com/data/Tensk",
		"http://travellermap.com/data/Aphlent",
		"http://travellermap.com/data/Randtred",
		"http://travellermap.com/data/Ruthless%20Veil",
		"http://travellermap.com/data/Uroac",
		"http://travellermap.com/data/Iphl",
		"http://travellermap.com/data/Qona",
		"http://travellermap.com/data/Qiask",
		"http://travellermap.com/data/Uaftdual",
		"http://travellermap.com/data/Orna",
		"http://travellermap.com/data/Noontask",
		"http://travellermap.com/data/Onoo",
		"http://travellermap.com/data/Dranon",
		"http://travellermap.com/data/Geerphli",
		"http://travellermap.com/data/Lila",
		"http://travellermap.com/data/Koirtrua",
		"http://travellermap.com/data/Ultret",
		"http://travellermap.com/data/Binaurie",
		"http://travellermap.com/data/Grevanne",
		"http://travellermap.com/data/Femengaal",
		"http://travellermap.com/data/Wobanna",
		"http://travellermap.com/data/Poinmaali",
		"http://travellermap.com/data/Hintrab",
		"http://travellermap.com/data/Ebollam",
		"http://travellermap.com/data/Tumluun",
		"http://travellermap.com/data/Yasktier",
		"http://travellermap.com/data/Uumpallu",
		"http://travellermap.com/data/Quavas",
		"http://travellermap.com/data/Indierri",
		"http://travellermap.com/data/Alila",
		"http://travellermap.com/data/Gudala",
		"http://travellermap.com/data/Giskakii",
		"http://travellermap.com/data/Incognita%20Ulterior",
		"http://travellermap.com/data/Coreward%20Shore",
		"http://travellermap.com/data/Greenwald's%20Beach",
		"http://travellermap.com/data/Narrow%20Transit",
		"http://travellermap.com/data/Sisyphus%20Ulterior",
		"http://travellermap.com/data/Pytheus%20Interior",
		"http://travellermap.com/data/Idirda",
		"http://travellermap.com/data/Kaalin%20Ulterior",
		"http://travellermap.com/data/Near%20Side%20of%20Yonder",
		"http://travellermap.com/data/Deepnight",
		"http://travellermap.com/data/Vilaakasii",
		"http://travellermap.com/data/Incognita%20Citerior",
		"http://travellermap.com/data/Central%20Bay",
		"http://travellermap.com/data/Far%20Shore%20of%20Yonder",
		"http://travellermap.com/data/Colaeus",
		"http://travellermap.com/data/Sisyphus%20Citerior",
		"http://travellermap.com/data/Pytheas",
		"http://travellermap.com/data/Diamond%20Scatter",
		"http://travellermap.com/data/Kaalin%20Citerior",
		"http://travellermap.com/data/First%20Prospect",
		"http://travellermap.com/data/Few%20Stars",
		"http://travellermap.com/data/No%20Shore",
		"http://travellermap.com/data/Big%20Empty",
		"http://travellermap.com/data/Open%20Rift",
		"http://travellermap.com/data/Last%20Prospect",
		"http://travellermap.com/data/Best%20Prospect",
		"http://travellermap.com/data/No%20Prospect",
		"http://travellermap.com/data/Black%20Night",
		"http://travellermap.com/data/Few%20Glimmers",
		"http://travellermap.com/data/Just%20Empty",
		"http://travellermap.com/data/Crossing",
		"http://travellermap.com/data/Far%20Shore",
		"http://travellermap.com/data/Far%20Shore%202",
		"http://travellermap.com/data/Annwn",
		"http://travellermap.com/data/Baltia",
		"http://travellermap.com/data/Brittia",
		"http://travellermap.com/data/Lemuria",
		"http://travellermap.com/data/Muspelheim",
		"http://travellermap.com/data/Hades",
		"http://travellermap.com/data/Harappa",
		"http://travellermap.com/data/Atlantis",
		"http://travellermap.com/data/Wilderlands",
		"http://travellermap.com/data/Ifingr",
		"http://travellermap.com/data/Styx",
		"http://travellermap.com/data/Tir%20NaNog",
		"http://travellermap.com/data/Olympus",
		"http://travellermap.com/data/Bifrost",
		"http://travellermap.com/data/Valhol",
		"http://travellermap.com/data/Hvergelmir",
		"http://travellermap.com/data/Acheron",
		"http://travellermap.com/data/Cathago",
		"http://travellermap.com/data/Arcadia",
		"http://travellermap.com/data/Troy",
		"http://travellermap.com/data/Gimli",
		"http://travellermap.com/data/Niflheim",
		"http://travellermap.com/data/Lethe",
		"http://travellermap.com/data/Hubur",
		"http://travellermap.com/data/Celadon",
		"http://travellermap.com/data/Naraka",
		"http://travellermap.com/data/Malvam",
		"http://travellermap.com/data/Elivagar",
		"http://travellermap.com/data/Riftsedge%20Coreward",
		"http://travellermap.com/data/Riftsedge%20Bridge",
		"http://travellermap.com/data/FSD%20Transition%20Spinward",
		"http://travellermap.com/data/LSD%20Transition%20One",
		"http://travellermap.com/data/ZSD%20Transition%20Two",
		"http://travellermap.com/data/LSD%20Transition%20Three",
		"http://travellermap.com/data/LSD%20Transition%20Four",
		"http://travellermap.com/data/LSD%20Transition%20Trailing",
		"http://travellermap.com/data/Big%20Island",
		"http://travellermap.com/data/Riftsedge%20Central",
		"http://travellermap.com/data/Voidshore%20One",
		"http://travellermap.com/data/Voidshore%20Two",
		"http://travellermap.com/data/Voidshore%20Three",
		"http://travellermap.com/data/LSD%20Transition%20Rimward",
		"http://travellermap.com/data/Voidshore%20Four",
		"http://travellermap.com/data/Voidshore%20Five",
		"http://travellermap.com/data/Voidshore%20Six",
		"http://travellermap.com/data/Voidshore%20Trailing",
		"http://travellermap.com/data/Riftsedge%20Rimward",
		"http://travellermap.com/data/VS-X",
		"http://travellermap.com/data/Voidshore%20Seven",
		"http://travellermap.com/data/Orion's%20Spit%20Coreward",
		"http://travellermap.com/data/Voidshore%20Eight",
		"http://travellermap.com/data/Voidshore%20Nine",
		"http://travellermap.com/data/Voidshore%20Ten",
		"http://travellermap.com/data/Voidshore%20Eleven",
		"http://travellermap.com/data/Voidshore%20Rimward",
		"http://travellermap.com/data/Orion's%20Spit%20Rimward",
		"http://travellermap.com/data/Yejiariebr",
		"http://travellermap.com/data/Zhiejqrinzho",
		"http://travellermap.com/data/Klajipl",
		"http://travellermap.com/data/Kazhekliepr",
		"http://travellermap.com/data/Chiajavlazh",
		"http://travellermap.com/data/Dliaprqriez",
		"http://travellermap.com/data/Pranzaklbraz",
		"http://travellermap.com/data/Stienzarikl",
		"http://travellermap.com/data/Zdechrebrvle",
		"http://travellermap.com/data/Tlialiedla",
		"http://travellermap.com/data/Fraklbizh",
		"http://travellermap.com/data/Tliblnzheflets",
		"http://travellermap.com/data/Nzievi",
		"http://travellermap.com/data/Preiel",
		"http://travellermap.com/data/Nezhatliebr",
		"http://travellermap.com/data/Siantsaia",
		"http://travellermap.com/data/Nchadla",
		"http://travellermap.com/data/Nchefrij",
		"http://travellermap.com/data/Zdielbeppria",
		"http://travellermap.com/data/Tavrbovliepl",
		"http://travellermap.com/data/Antsrish",
		"http://travellermap.com/data/Kepridlnchots",
		"http://travellermap.com/data/Evred",
		"http://travellermap.com/data/Chtatiate",
		"http://travellermap.com/data/Dliebriatia",
		"http://travellermap.com/data/Kliadli",
		"http://travellermap.com/data/Riadrazh",
		"http://travellermap.com/data/Iekrqre",
		"http://travellermap.com/data/Jiechnzhitsonj",
		"http://travellermap.com/data/Aplie",
		"http://travellermap.com/data/Eble",
		"http://travellermap.com/data/Vlofrkla",
		"http://travellermap.com/data/Jdibrirvianj",
		"http://travellermap.com/data/Ijar",
		"http://travellermap.com/data/Frajbriekrensh",
		"http://travellermap.com/data/Peklprozqratl",
		"http://travellermap.com/data/Flaflzhevrients",
		"http://travellermap.com/data/Anshnzhins",
		"http://travellermap.com/data/Lotsar",
		"http://travellermap.com/data/Niabrefvronz",
		"http://travellermap.com/data/Ienza",
		"http://travellermap.com/data/Vravrzha",
		"http://travellermap.com/data/Abresh",
		"http://travellermap.com/data/Kernzhez'a",
		"http://travellermap.com/data/Tlinchjiee",
		"http://travellermap.com/data/Iate",
		"http://travellermap.com/data/Drachabre",
		"http://travellermap.com/data/Jdodiafldla",
		"http://travellermap.com/data/Zii",
		"http://travellermap.com/data/Drierii",
		"http://travellermap.com/data/Voblezitl",
		"http://travellermap.com/data/Zhetsefr",
		"http://travellermap.com/data/Shiazhanche",
		"http://travellermap.com/data/Ploblvla",
		"http://travellermap.com/data/Ezhebl",
		"http://travellermap.com/data/Praklfrintsniadl",
		"http://travellermap.com/data/Feflolents",
		"http://travellermap.com/data/Dlavvreplents",
		"http://travellermap.com/data/Zietsebl",
		"http://travellermap.com/data/Zhejnzhiikl",
		"http://travellermap.com/data/Riafrtafrpriafr",
		"http://travellermap.com/data/Tlensbladrzhianzh",
		"http://travellermap.com/data/Sheqraflal",
		"http://travellermap.com/data/Pliajenzh",
		"http://travellermap.com/data/Nseianzh",
		"http://travellermap.com/data/Nzhajdibr",
		"http://travellermap.com/data/Nzhiaapl",
		"http://travellermap.com/data/Doklzots",
		"http://travellermap.com/data/Driklfetvipr",
		"http://travellermap.com/data/Jdencheplia",
		"http://travellermap.com/data/Shenzhtsenzh",
		"http://travellermap.com/data/Nialkridla",
		"http://travellermap.com/data/Enchakl",
		"http://travellermap.com/data/Riekllezha",
		"http://travellermap.com/data/Yikvrior",
		"http://travellermap.com/data/Fretvlobrpriet",
		"http://travellermap.com/data/Pliantiblbra",
		"http://travellermap.com/data/Plablshashchesh",
		"http://travellermap.com/data/Viashchieshiadl",
		"http://travellermap.com/data/Tlabraplzhied",
		"http://travellermap.com/data/Afdranz",
		"http://travellermap.com/data/Itsfiebl",
		"http://travellermap.com/data/Zhevreklnchi",
		"http://travellermap.com/data/Stiaklentsiefl",
		"http://travellermap.com/data/Difralfler",
		"http://travellermap.com/data/Eie",
		"http://travellermap.com/data/Tselidl",
		"http://travellermap.com/data/Zhiatienjiaz",
		"http://travellermap.com/data/Nili",
		"http://travellermap.com/data/Zenzhej",
		"http://travellermap.com/data/Shiadldriadash",
		"http://travellermap.com/data/Inshzish",
		"http://travellermap.com/data/Nshofref",
		"http://travellermap.com/data/Qrecha",
		"http://travellermap.com/data/Aed",
		"http://travellermap.com/data/Zdafeflzadr",
		"http://travellermap.com/data/Zdietablie",
		"http://travellermap.com/data/Fiaftashe",
		"http://travellermap.com/data/Tlapltsia'o",
		"http://travellermap.com/data/Azaz",
		"http://travellermap.com/data/Ichnzhipr",
		"http://travellermap.com/data/Eblia",
		"http://travellermap.com/data/Ze'shavrav",
		"http://travellermap.com/data/Ravrazhe",
		"http://travellermap.com/data/Ablaz",
		"http://travellermap.com/data/Idekl",
		"http://travellermap.com/data/Shiblbropli",
		"http://travellermap.com/data/Zdienzfiaia",
		"http://travellermap.com/data/Driebliepl",
		"http://travellermap.com/data/Ntetszif",
		"http://travellermap.com/data/Iebtladl",
		"http://travellermap.com/data/Febiaiadl",
		"http://travellermap.com/data/Tenshlatsvo",
		"http://travellermap.com/data/Loplia",
		"http://travellermap.com/data/Ijidl",
		"http://travellermap.com/data/Niechnchialbli",
		"http://travellermap.com/data/Qlivinchezh",
		"http://travellermap.com/data/Ee",
		"http://travellermap.com/data/Bliaazh",
		"http://travellermap.com/data/Ekrbriansh",
		"http://travellermap.com/data/Biaqrpraze",
		"http://travellermap.com/data/Sieriatsklinzh",
		"http://travellermap.com/data/Zentse",
		"http://travellermap.com/data/Tledrbreplebr",
		"http://travellermap.com/data/Vietrienzhits",
		"http://travellermap.com/data/Chtetaravl",
		"http://travellermap.com/data/Nzhenzie",
		"http://travellermap.com/data/Brelia",
		"http://travellermap.com/data/Pivchavia",
		"http://travellermap.com/data/Nzhernzhi",
		"http://travellermap.com/data/Ianse",
		"http://travellermap.com/data/Zhechinje",
		"http://travellermap.com/data/Jdeblinsiqr",
		"http://travellermap.com/data/Aviel",
		"http://travellermap.com/data/Prashtsintsanch",
		"http://travellermap.com/data/Qrefrnzhariefl",
		"http://travellermap.com/data/Ieviash",
		"http://travellermap.com/data/Stotsshiflezh",
		"http://travellermap.com/data/Frizhkladlncha",
		"http://travellermap.com/data/Chtijashal",
		"http://travellermap.com/data/Chetliashal",
		"http://travellermap.com/data/Etlnchofr",
		"http://travellermap.com/data/Zabrziklezh",
		"http://travellermap.com/data/Kozhdanzhinz",
		"http://travellermap.com/data/Flablenti",
		"http://travellermap.com/data/Setjefrshiatl",
		"http://travellermap.com/data/Kiafldliezhjol",
		"http://travellermap.com/data/Tsafrnchia",
		"http://travellermap.com/data/Ienjaz",
		"http://travellermap.com/data/Vedrabr",
		"http://travellermap.com/data/Driaflfiazlats",
		"http://travellermap.com/data/Brianch",
		"http://travellermap.com/data/Dliea",
		"http://travellermap.com/data/Pofdriblnchitl",
		"http://travellermap.com/data/Nevlieri",
		"http://travellermap.com/data/Tatlnjaie",
		"http://travellermap.com/data/Bliatsiebl",
		"http://travellermap.com/data/Favkranish",
		"http://travellermap.com/data/Zhenzhbrivtlo",
		"http://travellermap.com/data/Vikrvidrvria",
		"http://travellermap.com/data/Plontarbli",
		"http://travellermap.com/data/Azhpliabl",
		"http://travellermap.com/data/Prinjobliedl",
		"http://travellermap.com/data/Ia",
		"http://travellermap.com/data/Zietssha",
		"http://travellermap.com/data/Proanz",
		"http://travellermap.com/data/Tsebntsiatldlants",
		"http://travellermap.com/data/Kafvriadlklo",
		"http://travellermap.com/data/Izqri",
		"http://travellermap.com/data/Tezqraidl",
		"http://travellermap.com/data/Iavienj",
		"http://travellermap.com/data/Piebriedlzhie",
		"http://travellermap.com/data/Shantsnzekrradl",
		"http://travellermap.com/data/Brenchishshedl",
		"http://travellermap.com/data/Zdierntsiaplnzhiak",
		"http://travellermap.com/data/Bianchabr",
		"http://travellermap.com/data/Ezshiefl",
		"http://travellermap.com/data/Apliej",
		"http://travellermap.com/data/Pliqrtsans",
		"http://travellermap.com/data/Pietnshievlblaz",
		"http://travellermap.com/data/Bazhtloch",
		"http://travellermap.com/data/Zenzvraplblafl",
		"http://travellermap.com/data/Yrshovret",
		"http://travellermap.com/data/Kinsobe",
		"http://travellermap.com/data/Lieblnshafr",
		"http://travellermap.com/data/Lapred",
		"http://travellermap.com/data/Tleblmebranch",
		"http://travellermap.com/data/Drabrdlivr",
		"http://travellermap.com/data/Echianzh",
		"http://travellermap.com/data/Plochaf",
		"http://travellermap.com/data/Tlienchchiaa",
		"http://travellermap.com/data/Nzhaplats",
		"http://travellermap.com/data/Anen",
		"http://travellermap.com/data/Drichmaplie",
		"http://travellermap.com/data/Zhdiedlaol",
		"http://travellermap.com/data/Pifrinzhshe",
		"http://travellermap.com/data/Anshe",
		"http://travellermap.com/data/Ziadtleria",
		"http://travellermap.com/data/Iaqrof",
		"http://travellermap.com/data/Ashtsed",
		"http://travellermap.com/data/Dlianstsea",
		"http://travellermap.com/data/Oznshevl",
		"http://travellermap.com/data/Tlechchinblins",
		"http://travellermap.com/data/Krintefvriatl",
		"http://travellermap.com/data/Liea",
		"http://travellermap.com/data/Plieqrnsonznabr",
		"http://travellermap.com/data/Ashir",
		"http://travellermap.com/data/Iits",
		"http://travellermap.com/data/Biernchenchnshez",
		"http://travellermap.com/data/Finchkleqr",
		"http://travellermap.com/data/Favrnchettler",
		"http://travellermap.com/data/Fritsie",
		"http://travellermap.com/data/Shebplaf",
		"http://travellermap.com/data/Tlafla",
		"http://travellermap.com/data/Ebir",
		"http://travellermap.com/data/Zeliejiar",
		"http://travellermap.com/data/Zieltsanstsa",
		"http://travellermap.com/data/Zhazhjaievl",
		"http://travellermap.com/data/Dlea",
		"http://travellermap.com/data/Stakrzhivnchech",
		"http://travellermap.com/data/Ienjiej",
		"http://travellermap.com/data/Tlonchebre",
		"http://travellermap.com/data/Chtachntseknshe",
		"http://travellermap.com/data/Plianzhiavrzef",
		"http://travellermap.com/data/Katsazhje",
		"http://travellermap.com/data/Shtazheo",
		"http://travellermap.com/data/Iefriz",
		"http://travellermap.com/data/Ojbrevr",
		"http://travellermap.com/data/Iefliefr",
		"http://travellermap.com/data/Eqropl",
		"http://travellermap.com/data/Jeriavria",
		"http://travellermap.com/data/Zdiantnchoplflo",
		"http://travellermap.com/data/Sazhieits",
		"http://travellermap.com/data/Riadlblieda",
		"http://travellermap.com/data/Zharnjipribr",
		"http://travellermap.com/data/Nianjnzhanjebl",
		"http://travellermap.com/data/Enjzhad",
		"http://travellermap.com/data/Anchekr",
		"http://travellermap.com/data/Chellinzpripr",
		"http://travellermap.com/data/Itslafl",
		"http://travellermap.com/data/Jiebvlanzhinsh",
		"http://travellermap.com/data/Kamiet",
		"http://travellermap.com/data/Fripmiezh",
		"http://travellermap.com/data/Chenchdiklprebl",
		"http://travellermap.com/data/Tliaadl",
		"http://travellermap.com/data/Chinchianchnzie",
		"http://travellermap.com/data/Zdombrianchid",
		"http://travellermap.com/data/Sitflonchekl",
		"http://travellermap.com/data/Zillinshi",
		"http://travellermap.com/data/Chiantsiekrepl",
		"http://travellermap.com/data/Dliedlblienchikl",
		"http://travellermap.com/data/Niavrplikenzh",
		"http://travellermap.com/data/Zhiaklshaqrakl",
		"http://travellermap.com/data/Dloplae",
		"http://travellermap.com/data/Chtidlblevizh",
		"http://travellermap.com/data/Tledlvriantsha",
		"http://travellermap.com/data/Tlekantstiv",
		"http://travellermap.com/data/Frezeosh",
		"http://travellermap.com/data/Stachofrze",
		"http://travellermap.com/data/Chtabrbledrzhenj",
		"http://travellermap.com/data/Qrekleflzhonzh",
		"http://travellermap.com/data/Zdizntsiflnjebl",
		"http://travellermap.com/data/Senshiee",
		"http://travellermap.com/data/Aiez",
		"http://travellermap.com/data/Zinchiabr",
		"http://travellermap.com/data/Drebienzh",
		"http://travellermap.com/data/Chablidlblish",
		"http://travellermap.com/data/Keklnzeplivr",
		"http://travellermap.com/data/Pazhialnshiats",
		"http://travellermap.com/data/Vrivrbit",
		"http://travellermap.com/data/Jdanshiplshi",
		"http://travellermap.com/data/Kablaefr",
		"http://travellermap.com/data/Chaziprnshibl",
		"http://travellermap.com/data/Iodl",
		"http://travellermap.com/data/Tlienchtianshnzint",
		"http://travellermap.com/data/Replem",
		"http://travellermap.com/data/Sefqrefiabl",
		"http://travellermap.com/data/Banzenchnzhiaf",
		"http://travellermap.com/data/Sattsiapia",
		"http://travellermap.com/data/Laints",
		"http://travellermap.com/data/Zdedrshiaiam",
		"http://travellermap.com/data/Onzhie",
		"http://travellermap.com/data/Zdevrnchishnzadr",
		"http://travellermap.com/data/Eflntsapr",
		"http://travellermap.com/data/Siebrfizia",
		"http://travellermap.com/data/Kentsibia",
		"http://travellermap.com/data/Manziae",
		"http://travellermap.com/data/Klilab",
		"http://travellermap.com/data/Chelintsfliefl",
		"http://travellermap.com/data/Chtichbrae",
		"http://travellermap.com/data/Ziefrenz",
		"http://travellermap.com/data/Brebrai",
		"http://travellermap.com/data/Zhdienzblonshfo",
		"http://travellermap.com/data/Oka",
		"http://travellermap.com/data/Qliantfriazhia",
		"http://travellermap.com/data/Kablfratinch",
		"http://travellermap.com/data/Qrefriesh",
		"http://travellermap.com/data/Bobrfensjavr",
		"http://travellermap.com/data/Nchetsiens",
		"http://travellermap.com/data/Ebrikl",
		"http://travellermap.com/data/Iebe",
		"http://travellermap.com/data/Zheza",
		"http://travellermap.com/data/Nchiekle",
		"http://travellermap.com/data/Temja",
		"http://travellermap.com/data/Zieshieblbliaf",
		"http://travellermap.com/data/Shtebliakle",
		"http://travellermap.com/data/Sofvlianjdlet",
		"http://travellermap.com/data/Tlafrlakle",
		"http://travellermap.com/data/Era",
		"http://travellermap.com/data/Danchlito",
		"http://travellermap.com/data/Abrel",
		"http://travellermap.com/data/Fretszitse",
		"http://travellermap.com/data/Zhdielnjiensets",
		"http://travellermap.com/data/Fefrplalie",
		"http://travellermap.com/data/Bronzhiafr",
		"http://travellermap.com/data/Ikla",
		"http://travellermap.com/data/Chepiaebl",
		"http://travellermap.com/data/Ziedlnshech",
		"http://travellermap.com/data/Ichiz",
		"http://travellermap.com/data/Ziabtsrtl",
		"http://travellermap.com/data/Diplae",
		"http://travellermap.com/data/Blidlnzhevle",
		"http://travellermap.com/data/Pladreot",
		"http://travellermap.com/data/Zdizhzezhjia",
		"http://travellermap.com/data/Brenzhdredlel",
		"http://travellermap.com/data/Siavvreziaqr",
		"http://travellermap.com/data/Dreberpliat",
		"http://travellermap.com/data/Natzieliadl",
		"http://travellermap.com/data/Niklanchetl",
		"http://travellermap.com/data/Nzhablvlafl",
		"http://travellermap.com/data/Jdalabliakl",
		"http://travellermap.com/data/Ialie",
		"http://travellermap.com/data/Shachak",
		"http://travellermap.com/data/Miazhnaetl",
		"http://travellermap.com/data/Tseplodl",
		"http://travellermap.com/data/Rienzienzh",
		"http://travellermap.com/data/Dinsvianchivr",
		"http://travellermap.com/data/Bridlbrieriabl",
		"http://travellermap.com/data/Zialienjqrafl",
		"http://travellermap.com/data/Efent",
		"http://travellermap.com/data/Flilkianzo",
		"http://travellermap.com/data/Zieqrdralier",
		"http://travellermap.com/data/Prietsrebrpie",
		"http://travellermap.com/data/Ienchi",
		"http://travellermap.com/data/Blelia",
		"http://travellermap.com/data/Draziavr",
		"http://travellermap.com/data/Tiedlvlaklia",
		"http://travellermap.com/data/Tlakliri",
		"http://travellermap.com/data/Zhiznjiantsian",
		"http://travellermap.com/data/Zia",
		"http://travellermap.com/data/Nshienzflesh",
		"http://travellermap.com/data/Chatlbloshish",
		"http://travellermap.com/data/Ifliats",
		"http://travellermap.com/data/Chtettivrensh",
		"http://travellermap.com/data/Brafrshash",
		"http://travellermap.com/data/Ible",
		"http://travellermap.com/data/Qizojens",
		"http://travellermap.com/data/Renjaodr",
		"http://travellermap.com/data/Ieklliebl",
		"http://travellermap.com/data/Zdianozhi",
		"http://travellermap.com/data/Shiablvriebrvrie",
		"http://travellermap.com/data/Ieobl",
		"http://travellermap.com/data/Nietlee",
		"http://travellermap.com/data/Brietseqrie",
		"http://travellermap.com/data/Sieplnshotsebl",
		"http://travellermap.com/data/Tsanzshofr",
		"http://travellermap.com/data/Shanchafoch",
		"http://travellermap.com/data/Onsia",
		"http://travellermap.com/data/Tlenzhnzetl",
		"http://travellermap.com/data/Penchila",
		"http://travellermap.com/data/Taaz",
		"http://travellermap.com/data/Tlevrievl",
		"http://travellermap.com/data/Fradla",
		"http://travellermap.com/data/Nzefra",
		"http://travellermap.com/data/Kanchtsianzhnche",
		"http://travellermap.com/data/Ianchvlia",
		"http://travellermap.com/data/Fiezai",
		"http://travellermap.com/data/Miadlshiatie",
		"http://travellermap.com/data/Tsazhchiakraj",
		"http://travellermap.com/data/Efrpra",
		"http://travellermap.com/data/Ziablnjopi",
		"http://travellermap.com/data/Bliashnshatsfiapl",
		"http://travellermap.com/data/Stiefrniazhla",
		"http://travellermap.com/data/Frianchzidl",
		"http://travellermap.com/data/Chtanchzinzhbriz",
		"http://travellermap.com/data/Qlaklei",
		"http://travellermap.com/data/Kriplianzha",
		"http://travellermap.com/data/Vinzov",
		"http://travellermap.com/data/Dliedlvrietsiapl",
		"http://travellermap.com/data/Blefrnsha",
		"http://travellermap.com/data/Kiableqr",
		"http://travellermap.com/data/Dlavleshprenz",
		"http://travellermap.com/data/Blemzhiet",
		"http://travellermap.com/data/Fiefra",
		"http://travellermap.com/data/Iatlzez",
		"http://travellermap.com/data/Dliadltliashklesh",
		"http://travellermap.com/data/Dlavlitsbriv",
		"http://travellermap.com/data/Ovldanch",
		"http://travellermap.com/data/Tlonzhabriej",
		"http://travellermap.com/data/Zhievevre",
		"http://travellermap.com/data/Drebrvlif",
		"http://travellermap.com/data/Priashqrabnjans",
		"http://travellermap.com/data/Nshea",
		"http://travellermap.com/data/Drenchetsevr",
		"http://travellermap.com/data/Ienchnshia",
		"http://travellermap.com/data/Ieed",
		"http://travellermap.com/data/Ienzhopr",
		"http://travellermap.com/data/Amikl",
		"http://travellermap.com/data/Zhoblnsebe",
		"http://travellermap.com/data/Njenzhfrez",
		"http://travellermap.com/data/Zdiqrqrinsdlie",
		"http://travellermap.com/data/Moflrelzhanj",
		"http://travellermap.com/data/Iefrevr",
		"http://travellermap.com/data/Obrie",
		"http://travellermap.com/data/Vrochiqrats",
		"http://travellermap.com/data/Nshiafench",
		"http://travellermap.com/data/Kreblienchncho",
		"http://travellermap.com/data/Ncheblzevr",
		"http://travellermap.com/data/Chantsqrincha",
		"http://travellermap.com/data/Chetsazh",
		"http://travellermap.com/data/Menchnsienzh",
		"http://travellermap.com/data/Zieienzh",
		"http://travellermap.com/data/Tiafrientsinch",
		"http://travellermap.com/data/Zdoznsaqri",
		"http://travellermap.com/data/Chtebpraflnsiaz",
		"http://travellermap.com/data/Chienshnchia",
		"http://travellermap.com/data/Tlinshflechntsants",
		"http://travellermap.com/data/Priaqrtsanziesh",
		"http://travellermap.com/data/Driavlplodlavl",
		"http://travellermap.com/data/Iedobl",
		"http://travellermap.com/data/Zhabtlantenz",
		"http://travellermap.com/data/Tlishishidl",
		"http://travellermap.com/data/Dovnshotsents",
		"http://travellermap.com/data/Planchdetsifr",
		"http://travellermap.com/data/Iezab",
		"http://travellermap.com/data/Kladllavlia",
		"http://travellermap.com/data/Zhenzdliedl",
		"http://travellermap.com/data/Priadezer",
		"http://travellermap.com/data/Ziansliflvred",
		"http://travellermap.com/data/Bridzhetil",
		"http://travellermap.com/data/Shovrnchee",
		"http://travellermap.com/data/Chenshiatlietl",
		"http://travellermap.com/data/Drantkledlits",
		"http://travellermap.com/data/Atsja",
		"http://travellermap.com/data/Chtaklpiasha",
		"http://travellermap.com/data/Vletslonz",
		"http://travellermap.com/data/Alabl",
		"http://travellermap.com/data/Onzivr",
		"http://travellermap.com/data/Zinzhnchieqrbosh",
		"http://travellermap.com/data/Shenzhiave",
		"http://travellermap.com/data/Dlivliashzavr",
		"http://travellermap.com/data/Chtentsqrrcha",
		"http://travellermap.com/data/Liartipl",
		"http://travellermap.com/data/Anjnjie",
		"http://travellermap.com/data/Tlishienjtsaj",
		"http://travellermap.com/data/Chiakljenza",
		"http://travellermap.com/data/Inchats",
		"http://travellermap.com/data/Kranjvlie",
		"http://travellermap.com/data/Zhdechqrebir",
		"http://travellermap.com/data/Chanzchiazbrid",
		"http://travellermap.com/data/Oit",
		"http://travellermap.com/data/Bredlozhtso",
		"http://travellermap.com/data/Aknchiebl",
		"http://travellermap.com/data/Zhenshejiaz",
		"http://travellermap.com/data/Chtiashzhifel",
		"http://travellermap.com/data/Izkre",
		"http://travellermap.com/data/Dreshziach",
		"http://travellermap.com/data/Nzanznzhians",
		"http://travellermap.com/data/Fievivltsa",
		"http://travellermap.com/data/Fezenzhplens",
		"http://travellermap.com/data/Bienzete",
		"http://travellermap.com/data/Oti",
		"http://travellermap.com/data/Tlafrnchia",
		"http://travellermap.com/data/Etsel",
		"http://travellermap.com/data/Sekiajia",
		"http://travellermap.com/data/Kinchnche'mish",
		"http://travellermap.com/data/Blatiarnsi",
		"http://travellermap.com/data/Friazhiacho",
		"http://travellermap.com/data/Jedtsolesh",
		"http://travellermap.com/data/Dliflpletsepl",
		"http://travellermap.com/data/Tlianchbrinchki",
		"http://travellermap.com/data/Aints",
		"http://travellermap.com/data/Jdibrfliertsiash",
		"http://travellermap.com/data/Ianchle",
		"http://travellermap.com/data/Jeklnchaflabr",
		"http://travellermap.com/data/Fo'zhaflak",
		"http://travellermap.com/data/Pliblie",
		"http://travellermap.com/data/Tenzhnsema",
		"http://travellermap.com/data/Jebrneflrent",
		"http://travellermap.com/data/Nzintsziaz",
		"http://travellermap.com/data/Tliafklozhmiafr",
		"http://travellermap.com/data/Ntsatlil",
		"http://travellermap.com/data/Zhdensrafr",
		"http://travellermap.com/data/Kirnsianchanj",
		"http://travellermap.com/data/Chtansreplepl",
		"http://travellermap.com/data/Zhashshapllia",
		"http://travellermap.com/data/Ieplqriedl",
		"http://travellermap.com/data/Riazhvaflots",
		"http://travellermap.com/data/Avrent",
		"http://travellermap.com/data/Iaiech",
		"http://travellermap.com/data/Nazhfrieti",
		"http://travellermap.com/data/Nievoak",
		"http://travellermap.com/data/47%20G.%20Orionis",
		"http://travellermap.com/data/42%20Orionis",
		"http://travellermap.com/data/64%20G.%20Orionis",
		"http://travellermap.com/data/Alnitak",
		"http://travellermap.com/data/96%20G.%20Orionis",
		"http://travellermap.com/data/Eta%20Orionis",
		"http://travellermap.com/data/Pi-6%20Orionis",
		"http://travellermap.com/data/Meissa",
		"http://travellermap.com/data/Mintaka",
		"http://travellermap.com/data/Phi-1%20Orionis",
		"http://travellermap.com/data/25%20Orionis",
		"http://travellermap.com/data/Psi%20Orionis",
		"http://travellermap.com/data/Hatsya",
		"http://travellermap.com/data/Sigma%20Orionis",
		"http://travellermap.com/data/Pi-4%20Orionis",
		"http://travellermap.com/data/Alnilam",
		"http://travellermap.com/data/O%20Orionis",
		"http://travellermap.com/data/69%20G.%20Orionis",
		"http://travellermap.com/data/82%20G.%20Orionis",
		"http://travellermap.com/data/Upsilon%20Orionis",
		"http://travellermap.com/data/Omega%20Orionis",
		"http://travellermap.com/data/85%20G.%20Orionis",
		"http://travellermap.com/data/Joyce's%20Void",
		"http://travellermap.com/data/U%20Orionis",
		"http://travellermap.com/data/Theta-2%20Orionis",
		"http://travellermap.com/data/Fallow",
		"http://travellermap.com/data/Extent",
		"http://travellermap.com/data/Shadow%20Rift",
		"http://travellermap.com/data/Bourne",
		"http://travellermap.com/data/Divide",
		"http://travellermap.com/data/Halcyon",
		"http://travellermap.com/data/Far%20Home",
		"http://travellermap.com/data/Course",
		"http://travellermap.com/data/Abyss",
		"http://travellermap.com/data/Chasm",
		"http://travellermap.com/data/Gulf",
		"http://travellermap.com/data/Deep",
		"http://travellermap.com/data/Reikan",
		"http://travellermap.com/data/Ulund",
		"http://travellermap.com/data/Navarre",
		"http://travellermap.com/data/Suluru",
		"http://travellermap.com/data/Hirada",
		"http://travellermap.com/data/Coro",
		"http://travellermap.com/data/Palladian",
		"http://travellermap.com/data/Remoran",
		"http://travellermap.com/data/Archos",
		"http://travellermap.com/data/Mycene",
		"http://travellermap.com/data/Celeste",
		"http://travellermap.com/data/Magister",
		"http://travellermap.com/data/Jontell",
		"http://travellermap.com/data/Lucent",
		"http://travellermap.com/data/Murian",
		"http://travellermap.com/data/Lon%20Beon",
		"http://travellermap.com/data/Thrax",
		"http://travellermap.com/data/Kineda",
		"http://travellermap.com/data/Orsen",
		"http://travellermap.com/data/Denison",
		"http://travellermap.com/data/Wayland",
		"http://travellermap.com/data/Quell",
		"http://travellermap.com/data/Yearn",
		"http://travellermap.com/data/Leiden",
		"http://travellermap.com/data/Mageera",
		"http://travellermap.com/data/Elysium",
		"http://travellermap.com/data/Coraline",
		"http://travellermap.com/data/Wraith",
		"http://travellermap.com/data/Amarada",
		"http://travellermap.com/data/Forge",
		"http://travellermap.com/data/Garadin",
		"http://travellermap.com/data/Median",
		"http://travellermap.com/data/Tirell",
		"http://travellermap.com/data/Serenity",
		"http://travellermap.com/data/Perfection",
		"http://travellermap.com/data/Ledge",
		"http://travellermap.com/data/Phanic",
		"http://travellermap.com/data/Burden",
		"http://travellermap.com/data/Omicus",
		"http://travellermap.com/data/Hollow",
		"http://travellermap.com/data/Shandara",
		"http://travellermap.com/data/Range",
		"http://travellermap.com/data/Tarchon",
		"http://travellermap.com/data/Revenant",
		"http://travellermap.com/data/Kataran",
		"http://travellermap.com/data/Cauldron",
		"http://travellermap.com/data/Kalash",
		"http://travellermap.com/data/Turoman",
		"http://travellermap.com/data/Valiance",
		"http://travellermap.com/data/Toller",
		"http://travellermap.com/data/Palatine",
		"http://travellermap.com/data/Argent",
		"http://travellermap.com/data/Stand",
		"http://travellermap.com/data/Samardin",
		"http://travellermap.com/data/Pestilent",
		"http://travellermap.com/data/Ley",
		"http://travellermap.com/data/Maranatha-Alkahest",
		"http://travellermap.com/data/Glimmerdrift%20Reaches",
		"http://travellermap.com/data/Crucis%20Margin",
		"http://travellermap.com/data/Tagret",
		"http://travellermap.com/data/Vanguard%20Reaches",
		"http://travellermap.com/data/The%20Beyond",
		"http://travellermap.com/data/Varan",
		"http://travellermap.com/data/Dark%20Sea",
		"http://travellermap.com/data/The%20Beyond",
		"http://travellermap.com/data/Precipice",
		"http://travellermap.com/data/Rigel",
		"http://travellermap.com/data/Foreven",
		"http://travellermap.com/data/Fulani",
		"http://travellermap.com/data/Meshan",
		"http://travellermap.com/data/Morning%20Star",
		"http://travellermap.com/data/Ares",
		"http://travellermap.com/data/Anniversary",
		"http://travellermap.com/data/Nowhere",
		"http://travellermap.com/data/Marischal",
		"http://travellermap.com/data/Calidan",
		"http://travellermap.com/data/Rosalis%20Cluster",
		"http://travellermap.com/data/Fantana%20Spur",
		"http://travellermap.com/data/Trans%20Dolovia",
		"http://travellermap.com/data/Lemon%20and%20Gold",
	}
}

func allHexes() []string {
	horS := []string{}
	for hor := 1; hor <= 40; hor++ {
		hS := strconv.Itoa(hor)
		if hor < 10 {
			hS = "0" + hS
		}
		horS = append(horS, hS)
	}
	verS := []string{}
	for ver := 1; ver <= 32; ver++ {
		vS := strconv.Itoa(ver)
		if ver < 10 {
			vS = "0" + vS
		}
		verS = append(verS, vS)
	}
	hex := []string{}
	for _, v := range verS {
		for _, h := range horS {
			hex = append(hex, v+h)
		}
	}
	return hex
}
