package assets

const (
	C1 = iota
	C2
	C3
	C4
	C5
	C6
	CS
	CP
	Strength
	Dexterity
	Agility
	Grace
	Endurance
	Stamina
	Vigor
	Intelligence
	Education
	Training
	Instinct
	Social
	Charisma
	Caste
	Sanity
	Psionics
	SKILL_Admin
	SKILL_Advocate
	SKILL_Animals
	SKILL_Athlete
	SKILL_Broker
	SKILL_Bureaucrat
	SKILL_Comms
	SKILL_Computer
	SKILL_Counsellor
	SKILL_Designer
	SKILL_Diplomat
	SKILL_Driver
	SKILL_Explosives
	SKILL_FleetTactics
	SKILL_Flyer
	SKILL_Forensics
	SKILL_Gambler
	SKILL_HighG
	SKILL_HostileEnviron
	SKILL_JOT
	SKILL_Language
	SKILL_Leader
	SKILL_Liaison
	SKILL_NavalArchitect
	SKILL_Seafarer
	SKILL_Stealth
	SKILL_Strategy
	SKILL_Streetwise
	SKILL_Survey
	SKILL_Survival
	SKILL_Tactics
	SKILL_Teacher
	SKILL_Trader
	SKILL_VaccSuit
	SKILL_ZeroG
	SKILL_Astrogator
	SHIP_Engineer
	SHIP_Gunner
	SHIP_Medic
	SHIP_Pilot
	SHIP_Sensors
	SHIP_Steward
	TRADE_Biologics
	TRADE_Craftsman
	TRADE_Electronics
	TRADE_Fluidics
	TRADE_Gravitics
	TRADE_Magnetics
	TRADE_Mechanic
	TRADE_Photonics
	TRADE_Polymers
	TRADE_Programmer
	ART_Actor
	ART_Artist
	ART_Author
	ART_Chef
	ART_Dancer
	ART_Musician
	SOLDER_Fighter
	SOLDER_ForwardObserver
	SOLDER_HeavyWeapons
	SOLDER_Navigator
	SOLDER_Recon
	SOLDER_Sapper
	TALENT_Compute
	TALENT_Empath
	TALENT_Hibernate
	TALENT_Hypno
	TALENT_Intuition
	TALENT_Math
	TALENT_MemAware
	TALENT_Memorize
	TALENT_MemPercept
	TALENT_MemScent
	TALENT_MemSight
	TALENT_MemSound
	TALENT_Morph
	TALENT_Rage
	TALENT_SoundMimic
	PRSNL_Carouse
	PRSNL_Query
	PRSNL_Persuade
	PRSNL_Command
	INTUIT_Curiosity
	INTUIT_Insight
	INTUIT_Luck
	KNOWLEDGE_Rider
	KNOWLEDGE_Teamster
	KNOWLEDGE_Trainer
	KNOWLEDGE_ACV
	KNOWLEDGE_Automotive
	KNOWLEDGE_GravDriver
	KNOWLEDGE_Legged
	KNOWLEDGE_Mole
	KNOWLEDGE_Tracked
	KNOWLEDGE_Wheeled
	KNOWLEDGE_JumpDrives
	KNOWLEDGE_LifeSupport
	KNOWLEDGE_ManeuverDrive
	KNOWLEDGE_PowerSystems
	KNOWLEDGE_BattleDress
	KNOWLEDGE_Beams
	KNOWLEDGE_Blades
	KNOWLEDGE_Exotics
	KNOWLEDGE_SlugThrowers
	KNOWLEDGE_Sprays
	KNOWLEDGE_Unarmed
	KNOWLEDGE_Aeronautics
	KNOWLEDGE_Flapper
	KNOWLEDGE_GravFlyer
	KNOWLEDGE_LTA
	KNOWLEDGE_Rotor
	KNOWLEDGE_Winged
	KNOWLEDGE_BayWeapons
	KNOWLEDGE_Ortillery
	KNOWLEDGE_Screens
	KNOWLEDGE_Spines
	KNOWLEDGE_Turrets
	KNOWLEDGE_Artillery
	KNOWLEDGE_Launcher
	KNOWLEDGE_Ordnance
	KNOWLEDGE_WMD
	KNOWLEDGE_SmallCraft
	KNOWLEDGE_SpacecraftACS
	KNOWLEDGE_SpacecraftBCS
	KNOWLEDGE_Aquanautics
	KNOWLEDGE_GravSea
	KNOWLEDGE_Boat
	KNOWLEDGE_ShipSea
	KNOWLEDGE_Sub
	KNOWLEDGE_Archeology
	KNOWLEDGE_Biology
	KNOWLEDGE_Chemistry
	KNOWLEDGE_History
	KNOWLEDGE_Linguistics
	KNOWLEDGE_Philosophy
	KNOWLEDGE_Physics
	KNOWLEDGE_Planetology
	KNOWLEDGE_Psionicology
	KNOWLEDGE_Psychohistory
	KNOWLEDGE_Psychology
	KNOWLEDGE_Robotics
	KNOWLEDGE_Sophontology
	KNOWLEDGE_Specialized
)

type Asset interface {
	Value() int
	Code() int
	Name() int
}
